(()=>{'use strict';
const E=CrystalCommand,$=id=>document.getElementById(id),canvas=$('battle'),renderer=CrystalRenderer.create(canvas);
let state=E.create(),side=0,v=E.view(state,0),running=false,paused=false,online=false,room=null,wire=null,connected=false,peerSeen=0,peerVisible=true,seq=0,lastSeq=-1,frameAt=0,acc=0,snapshotAt=0,hbAt=0,selection=[],palette='train',placing=null,order='attack',rallyMode=false,resourceId=null,pointer=null,drag=null,busy=false,muted=localStorage.getItem('crystalSound')==='off',audio,lastFx=0,lastNotice=0,peerReady=false,commandsAt=0,commandCount=0,lastRoomPoll=0;
function notice(s){$('message').textContent=s;$('message').hidden=false;lastNotice=performance.now()}
function sound(kind){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});if(audio.currentTime-lastFx<.08)return;lastFx=audio.currentTime;
 const tones=kind==='ready'?[[740,1040,0,.13],[1040,1480,.12,.18]]:kind==='deposit'?[[860,1320,0,.16],[1320,1700,.07,.1]]:kind==='shot'?[[1400,150,0,.12],[180,65,0,.1]]:kind==='build'?[[220,660,0,.18],[440,880,.1,.13]]:[[460,800,0,.1]];
 for(const [from,to,delay,duration]of tones){const o=audio.createOscillator(),g=audio.createGain(),at=audio.currentTime+delay;o.type=kind==='shot'?'triangle':'sine';o.frequency.setValueAtTime(from,at);o.frequency.exponentialRampToValueAtTime(to,at+duration);g.gain.setValueAtTime(.001,at);g.gain.linearRampToValueAtTime(kind==='shot'?.018:.024,at+.008);g.gain.exponentialRampToValueAtTime(.001,at+duration);o.connect(g).connect(audio.destination);o.start(at);o.stop(at+duration+.02)}
}catch{}}

function own(type){return v.entities.filter(e=>e.side===side&&(!type||e.type===type))}
function selectedBuilding(){return own().find(e=>selection.includes(e.id)&&!E.TYPES[e.type].supply)||own('base')[0]}
function formatTime(t){return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')}
function hud(){document.body.classList.toggle('game-active',running);document.body.classList.toggle('cc-menu',!running);const p=v.player;$('crystals').textContent=Math.floor(p.crystals);$('supply').textContent=p.used+' / '+p.cap;$('baseHp').textContent=own('base').reduce((n,e)=>n+Math.max(0,Math.ceil(e.hp)),0);$('clock').textContent=formatTime(v.time);$('connection').firstChild.textContent=online?(paused?'PAUSED':'FRIEND BATTLE'):'PRACTICE';$('pause').textContent=paused?'Resume':'Pause';$('pause').disabled=!running||online;$('quit').disabled=!running;$('context').textContent=placing?`Place ${E.TYPES[placing].name}: tap clear ground near your Miners.`:selection.length?`${selection.length===1?(E.TYPES[v.entities.find(e=>e.id===selection[0])?.type]?.name||'Unit'):selection.length+' units'} selected · ${order==='attack'?'tap to move & fight':'tap to move'}${selectedBuilding()?.queue.length?' · '+selectedBuilding().queue.length+' queued':''}`:'Tap a unit or use Army / Miners. Drag to pan.';selection=selection.filter(id=>v.entities.some(e=>e.id===id));const chosen=v.entities.filter(e=>selection.includes(e.id)),selected=chosen[0];$('selectionStatus').hidden=!selected;
 if(selected){const d=E.TYPES[selected.type],health=chosen.reduce((n,e)=>n+e.hp,0)/chosen.reduce((n,e)=>n+e.maxHp,0);$('selectionName').textContent=chosen.length===1?d.name:chosen.length+' units';$('selectionDetail').textContent=chosen.length===1?(selected.research?'Research · '+selected.research.kind+' '+selected.research.level+' · '+Math.ceil(selected.research.remaining)+'s':selected.type==='base'?v.entities.filter(e=>e.type==='worker'&&e.home===selected.id).length+' Miners · '+Math.floor(v.crystals.filter(n=>Math.hypot(n.x-selected.x,n.y-selected.y)<9).reduce((sum,n)=>sum+n.left,0)).toLocaleString()+' crystals nearby':selected.build?'Assembling · '+Math.ceil(selected.build)+'s':selected.queue.length?'Training · '+selected.queue.length+' queued':Math.ceil(selected.hp)+' / '+selected.maxHp+' HP'):'Ready for orders';$('selectionHealth').style.width=Math.max(0,health*100)+'%';$('selectionHealth').classList.toggle('damaged',health<.35)}
 const node=v.crystals.find(n=>n.id===resourceId);if(node){$('selectionStatus').hidden=false;$('selectionName').textContent=node.rich?'Rich crystal field':'Crystal patch';$('selectionDetail').textContent=Math.floor(node.left).toLocaleString()+' remaining · '+v.entities.filter(e=>e.type==='worker'&&e.patch===node.id).length+' Miners';$('selectionHealth').classList.remove('damaged');$('selectionHealth').style.width=Math.max(0,node.left/node.initial*100)+'%'}
 $('setRally').hidden=palette!=='train'||!selected||!['base','factory'].includes(selected.type);$('setRally').classList.toggle('active',rallyMode);$('setRally').setAttribute('aria-pressed',String(rallyMode));$('setRally').disabled=!running;
 for(const b of $('palette').querySelectorAll('[data-research]')){const kind=b.dataset.research,level=kind==='weapons'?p.upgrade:p.armor,lab=selectedBuilding(),research=v.entities.find(e=>e.side===side&&e.research?.kind===kind)?.research;b.dataset.cost=(kind==='weapons'?150:125)+100*level;b.querySelector('.tech-name').textContent=research?kind[0].toUpperCase()+kind.slice(1)+' · '+Math.ceil(research.remaining)+'s':kind[0].toUpperCase()+kind.slice(1)+' '+Math.min(3,level+1);b.querySelector('small').textContent=level>=3?'Fully researched':research?'Researching…':'◈ '+b.dataset.cost+' · '+((kind==='weapons'?18:16)+level*8)+'s';b.dataset.unavailable=String(!!research||!!lab?.research||level>=3)}
 for(const b of $('palette').querySelectorAll('[data-kind]')){b.classList.toggle('active',b.dataset.kind===placing);b.setAttribute('aria-pressed',String(b.dataset.kind===placing))}
 const factories=own('factory'),army=own().filter(e=>E.TYPES[e.type].supply&&e.type!=='worker');$('hint').textContent=rallyMode?'Tap a destination or crystal patch for new units.':placing?'Tap clear ground near your Miners to place '+E.TYPES[placing].name:factories.some(e=>e.build)?'Factory assembling · your Miners are still collecting.':army.length>=3?'Army ready · select Army, then tap a destination to attack.':factories.some(e=>e.queue.length)?'Army assembling · keep mining and scout your rival.':factories.some(e=>!e.build)?'Tap your factory to train Strikers. Scouts reveal the map.':'Miners are collecting. Train workers or build your first factory.';
 const count=p.used;for(const b of $('palette').querySelectorAll('button'))b.disabled=!running||b.dataset.unavailable==='true'||(Number(b.dataset.cost)>p.crystals);if(count>p.cap)$('supply').style.color='#ff9a80';else $('supply').style.color=''}
function showPalette(){const el=$('palette');el.dataset.mode=palette;el.replaceChildren();const producer=selectedBuilding();const kinds=palette==='build'?['factory','relay','turret','lab','base']:producer?.type==='factory'?['laser','siege']:producer?.type==='lab'?[]:['worker','scout'];for(const kind of kinds){const d=E.TYPES[kind],b=document.createElement('button');b.dataset.cost=d.cost;b.dataset.kind=kind;b.innerHTML='<span class="cc-unit-symbol" aria-hidden="true">'+CrystalArt.icon(kind)+'</span><span>'+d.name+'</span>'+ '<small>◈ '+d.cost+(d.supply?' · '+d.supply+' supply':'')+'</small>';b.addEventListener('click',()=>{if(!running)return;sound('click');if(palette==='build'){placing=placing===kind?null:kind;$('hint').textContent='Tap clear ground near your Miners to place '+d.name;hud()}else issue({type:'train',id:selectedBuilding()?.id,kind})});el.append(b)}if(palette==='train'&&producer?.type==='lab'){for(const kind of ['weapons','armor']){const b=document.createElement('button');b.dataset.research=kind;b.innerHTML='<span class="cc-unit-symbol" aria-hidden="true">'+CrystalArt.icon(kind==='weapons'?'laser':'siege')+'</span><span class="tech-name"></span><small></small>';b.onclick=()=>issue({type:'upgrade',id:producer.id,kind});el.append(b)}}$('trainTab').classList.toggle('active',palette==='train');$('buildTab').classList.toggle('active',palette==='build')}
function issue(c){if(!running||paused)return;if(online&&side===1){wire?.send({type:'command',seq:++seq,command:c});return{ok:true,pending:true}}const result=E.command(state,side,c);if(!result.ok)notice(result.message);else sound(c.type==='build'?'build':'click');v=E.view(state,side);hud();return result}
function resetBattle(practice){state=E.create({practice});v=E.view(state,side);selection=[v.entities.find(e=>e.side===side&&e.type==='base').id];renderer.center(side?33:6,side?33:6);placing=null;rallyMode=false;resourceId=null;palette='train';paused=false;running=true;acc=0;peerSeen=performance.now();$('lobby').hidden=true;$('results').hidden=true;$('hint').textContent='Miners are collecting. Train workers or build your first factory.';showPalette();hud()}
function finish(){if(!running)return;running=false;$('confirm').hidden=true;const won=v.winner===side;$('resultTitle').textContent=v.winner===null?'Battle ended':won?'VICTORY':'DEFEAT';$('resultText').textContent=v.reason;$('results').dataset.outcome=won?'victory':v.winner===null?'draw':'defeat';$('resultStats').innerHTML='<div><b>'+v.player.kills+'</b><span>DEFEATED</span></div><div><b>'+Math.floor(v.player.mined)+'</b><span>CRYSTALS MINED</span></div><div><b>'+formatTime(v.time)+'</b><span>BATTLE TIME</span></div>';$('results').hidden=false;hud();if(online&&side===0)wire?.send({type:'snapshot',view:E.view(state,1),paused:false});}
function onWire(p){peerSeen=performance.now();if(p.type==='heartbeat'){if((p.gameVersion||1)!==E.VERSION){peerReady=false;peerVisible=false;const message='Game updated · both players must refresh before joining.';if($('message').textContent!==message)notice(message);$('roomStatus').textContent=message;return}peerVisible=p.visible===true;peerReady=p.ready===true;return}
 if(side===0){if(p.type==='command'&&running&&Number.isSafeInteger(p.seq)&&p.seq>lastSeq&&p.command){lastSeq=p.seq;const now=performance.now();if(now-commandsAt>1000){commandsAt=now;commandCount=0}if(++commandCount>12)return;const result=E.command(state,1,p.command);if(!result.ok)wire.send({type:'notice',message:result.message});if(state.ended){v=E.view(state,0);finish()}}
 }else if(p.type==='snapshot'&&p.view?.version===E.VERSION&&p.view.side===1){if(p.view.tick<v.tick&&running)return;v=p.view;paused=!!p.paused;if(!running&&!v.ended){running=true;$('lobby').hidden=true;selection=[own('base')[0]?.id].filter(Boolean);renderer.center(33,33);showPalette()}hud();if(v.ended)finish()}
 else if(side===1&&p.type==='notice'&&typeof p.message==='string')notice(p.message.slice(0,160));
 if(p.type==='end'){notice('Your friend left the room');if(running){if(side===0){state.ended=true;state.winner=null;state.reason='Opponent disconnected'}v={...v,ended:true,winner:null,reason:'Opponent disconnected'};finish()}else $('roomStatus').textContent='Your friend left. Leave this room to create another.'}
}
async function roomAction(type){if(busy)return;busy=true;const gen=++connectionGeneration;$('lobbyError').textContent='';$('authLink').hidden=true;for(const id of['createRoom','joinRoom'])$(id).disabled=true;
 try{room=await CrystalNetwork.action(type,type==='join'?$('roomInput').value.trim().toUpperCase():null);side=room.side;online=true;running=false;state=E.create();v=E.view(state,side);renderer.center(side?33:6,side?33:6);selection=[];lastSeq=-1;seq=Date.now()*1000;peerReady=false;peerSeen=0;peerVisible=true;$('roomPane').hidden=false;$('roomCode').textContent=room.code;$('roomStatus').textContent='Connecting…';$('joinForm').hidden=true;
  wire=CrystalNetwork.connect(room,onWire,(ok,error)=>{if(gen!==connectionGeneration)return;connected=ok;if(!ok){$('roomStatus').textContent='Connecting…';if(running)notice('Connection interrupted. Reconnecting…')}else $('roomStatus').textContent=side===0?'Share the code with your friend.':'Connected. Waiting for the host…';if(error instanceof Error)$('lobbyError').textContent=error.message});
 }catch(error){$('lobbyError').textContent=error.message||'Room unavailable';if(/sign in/i.test(error.message))$('authLink').hidden=false;online=false;room=null}
 finally{busy=false;for(const id of['createRoom','joinRoom'])$(id).disabled=false}
}
let connectionGeneration=0;
async function leaveRoom(){++connectionGeneration;if(wire){await wire.send({type:'end'});await wire.close()}if(room)try{await CrystalNetwork.action('close',null,room.id)}catch{}wire=null;room=null;online=false;connected=false;peerReady=false;side=0;$('roomPane').hidden=true;}
function renderLoop(now){const dt=Math.min(.1,(now-frameAt)/1000||0);frameAt=now;
 if(online&&wire){if(now-hbAt>800){hbAt=now;wire.send({type:'heartbeat',visible:!document.hidden,ready:true,gameVersion:E.VERSION})}
  if(!running&&!state.ended&&side===0&&connected&&peerReady){resetBattle(false);notice('Friend connected. Battle started!')}
  if(running){paused=!connected||!peerVisible||document.hidden||now-peerSeen>4500;if(now-peerSeen>60000){v={...v,ended:true,winner:null,reason:'Connection lost · battle ended'};if(side===0){state.ended=true;state.winner=null;state.reason=v.reason}finish()}}
  if(now-lastRoomPoll>3000){lastRoomPoll=now;/* Heartbeats establish peer readiness; never start from an unverified row. */}
 }
 if(running&&(!online||side===0)&&!paused){acc+=dt;let steps=0;while(acc>=E.STEP&&steps++<4){E.tick(state);acc-=E.STEP}v=E.view(state,side);if(v.events.some(e=>e.type==='shot'))sound('shot');else if(v.events.some(e=>e.type==='trained'&&e.side===side))sound('ready');else if(v.events.some(e=>e.type==='deposit'))sound('deposit');if(state.ended)finish()}
 if(online&&side===0&&running&&connected&&now-snapshotAt>220){snapshotAt=now;wire.send({type:'snapshot',view:E.view(state,1),paused})}
 if(running&&now%250<40)hud();if(!paused)renderer.render(v,{selection,build:placing,pointer,resourceId});else renderer.render(v,{selection,paused:true,resourceId});if(lastNotice&&now-lastNotice>3500)$('message').hidden=true;requestAnimationFrame(renderLoop);
}
$('practice').onclick=async()=>{if(busy)return;sound('click');await leaveRoom();resetBattle(true)};
$('createRoom').onclick=()=>roomAction('create');$('showJoin').onclick=()=>{$('joinForm').hidden=!$('joinForm').hidden;$('roomInput').focus()};$('joinRoom').onclick=()=>roomAction('join');$('cancelRoom').onclick=async()=>{await leaveRoom();$('roomStatus').textContent='';};
$('copyRoom').onclick=async()=>{const link=new URL('crystal-command.html',location.href);link.searchParams.set('room',room.code);try{await navigator.clipboard.writeText(link.href);$('roomStatus').textContent='Invite link copied!'}catch{$('roomStatus').textContent='Share room code '+room.code}};
$('selectArmy').onclick=()=>{placing=null;rallyMode=false;resourceId=null;selection=own().filter(e=>E.TYPES[e.type].supply&&e.type!=='worker').map(e=>e.id);if(!selection.length)notice('Train Scouts at your base or Strikers at a factory');hud()};
$('selectMiners').onclick=()=>{placing=null;rallyMode=false;resourceId=null;selection=own('worker').map(e=>e.id);hud()};$('trainTab').onclick=()=>{palette='train';placing=null;rallyMode=false;showPalette();hud()};$('buildTab').onclick=()=>{palette='build';rallyMode=false;showPalette();hud()};$('setRally').onclick=()=>{placing=null;resourceId=null;rallyMode=!rallyMode;hud()};$('zoomIn').onclick=()=>renderer.zoomBy(.15);$('zoomOut').onclick=()=>renderer.zoomBy(-.15);$('home').onclick=()=>{const b=own('base')[0];if(b){renderer.center(b.x,b.y);selection=[b.id];resourceId=null;rallyMode=false;palette='train';placing=null;showPalette();hud()}};
$('orderMode').onclick=()=>{order=order==='attack'?'move':'attack';$('orderMode').textContent=order==='attack'?'⚔ Attack-move':'➜ Move only';hud()};
$('pause').onclick=()=>{if(running&&!online){paused=!paused;hud()}};
function askQuit(event){if(running){event?.preventDefault();$('quitText').textContent=online?'Quitting surrenders this battle to your friend.':'Your current practice battle will end.';$('confirm').hidden=false;$('keepPlaying').focus();if(!online)paused=true}}
$('quit').onclick=askQuit;$('back').onclick=askQuit;$('keepPlaying').onclick=()=>{$('confirm').hidden=true;if(!online)paused=false};$('confirmQuit').onclick=async()=>{$('confirm').hidden=true;if(online){paused=false;issue({type:'surrender'});if(side===1){v={...v,ended:true,winner:0,reason:'Commander surrendered'};finish()}}else{state.ended=true;state.winner=1;state.reason='Practice ended';v=E.view(state,0);finish()}};
$('again').onclick=async()=>{await leaveRoom();state=E.create();v=E.view(state,0);paused=false;running=false;selection=[];resourceId=null;rallyMode=false;$('results').hidden=true;$('lobby').hidden=false;renderer.center(6,6);showPalette();hud()};
$('sound').onclick=()=>{muted=!muted;localStorage.setItem('crystalSound',muted?'off':'on');$('sound').textContent=muted?'♫ Off':'♫ On';$('sound').setAttribute('aria-pressed',String(!muted));if(!muted)sound('click')};if(muted){$('sound').textContent='♫ Off';$('sound').setAttribute('aria-pressed','false')}
function local(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
canvas.addEventListener('pointerdown',e=>{if(!running)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const p=local(e);drag={id:e.pointerId,start:p,last:p,moved:false};pointer=p});
canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;e.preventDefault();const p=local(e);pointer=p;if(Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>7)drag.moved=true;if(drag.moved)renderer.pan(p.x-drag.last.x,p.y-drag.last.y);drag.last=p});
canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const p=local(e),moved=drag.moved;drag=null;if(moved||paused)return;if(renderer.minimap(p.x,p.y))return;const at=renderer.world(p.x,p.y);if(rallyMode){const n=renderer.resourceHit(v,p.x,p.y)||v.crystals.find(n=>Math.hypot(n.x-at.x,n.y-at.y)<1.3);const result=issue({type:'rally',id:selectedBuilding()?.id,x:n?.x??at.x,y:n?.y??at.y,target:n?.id});if(result?.ok){rallyMode=false;notice('Rally point set · new units head there automatically.')}hud();return}if(placing){const kind=placing,result=issue({type:'build',kind,x:at.x,y:at.y});if(result?.ok){placing=null;$('hint').textContent=E.TYPES[kind].name+' assembling'+(kind==='factory'?' · tap it when ready to train your army.':'.')}hud();return}const hit=renderer.hit(v,p.x,p.y);if(hit&&hit.side===side){selection=[hit.id];resourceId=null;rallyMode=false;placing=null;palette='train';showPalette();hud();return}const n=renderer.resourceHit(v,p.x,p.y)||v.crystals.find(n=>Math.hypot(n.x-at.x,n.y-at.y)<1.3);if(n&&selection.some(id=>own('worker').some(e=>e.id===id)))issue({type:'mine',ids:selection,x:n.x,y:n.y,target:n.id});else if(n){resourceId=n.id;selection=[];hud()}else if(selection.length)issue({type:order,ids:selection,x:at.x,y:at.y});else notice('Select Army or Miners first')});
canvas.addEventListener('pointercancel',()=>{drag=null});canvas.addEventListener('lostpointercapture',()=>{drag=null});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(!online&&running)paused=true;wire?.send({type:'heartbeat',visible:false,ready:true,gameVersion:E.VERSION});audio?.suspend()}else wire?.send({type:'heartbeat',visible:true,ready:true,gameVersion:E.VERSION})});window.addEventListener('pagehide',()=>{wire?.close()});
document.addEventListener('keydown',e=>{if(e.target.closest('input'))return;if(e.key==='Escape'){if(placing||rallyMode){placing=null;rallyMode=false;hud()}else if(!$('confirm').hidden)$('keepPlaying').click();else askQuit()}if(e.key==='a')$('selectArmy').click();if(e.key==='h')$('home').click();if(e.key==='r'&&!$('setRally').hidden)$('setRally').click();if(e.key==='b')$('buildTab').click();if(e.key===' '&&!online){e.preventDefault();$('pause').click()}});
const code=new URLSearchParams(location.search).get('room');if(code){$('joinForm').hidden=false;$('roomInput').value=code.slice(0,8).toUpperCase()}
showPalette();hud();requestAnimationFrame(renderLoop);
// Inspectable development harness; no reward hooks or production permissions.
window.CrystalGame={get view(){return v},get state(){return state},get running(){return running},get side(){return side},issue,renderer};
})();
