(()=>{
'use strict';
const E=NeonBreachEngine,game='neonBreach',canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),message=document.getElementById('arenaMessage'),pad=document.getElementById('movePad'),knob=document.getElementById('moveKnob'),fireButton=document.getElementById('fireButton'),els=Object.fromEntries(['score','health','wave','plays','balance','gameStatus','startButton'].map(id=>[id,document.getElementById(id)]));
let state=E.create(),running=false,starting=false,paused=false,last=0,raf=0,moveId=null,aimId=null,fireId=null,aimX=0,joy={forward:0,strafe:0},keys=new Set(),pauseControl;
const FOV=1.25;
function resetInput(){moveId=aimId=fireId=null;joy={forward:0,strafe:0};keys.clear();knob.style.transform='';fireButton.classList.remove('firing')}
function chrome(){els.score.textContent=state.score;els.health.textContent=state.player.hp;els.wave.textContent=Math.max(1,state.wave);els.plays.textContent=Arcade.remaining(game);els.balance.textContent=Arcade.number('points').toLocaleString()}
function status(text,active){els.gameStatus.textContent=text;els.gameStatus.classList.toggle('running',!!active);document.body.classList.toggle('game-active',!!active)}
function render(){const w=canvas.width,h=canvas.height,horizon=h*.48,p=state.player;ctx.fillStyle='#090d26';ctx.fillRect(0,0,w,horizon);const floor=ctx.createLinearGradient(0,horizon,0,h);floor.addColorStop(0,'#101531');floor.addColorStop(1,'#073546');ctx.fillStyle=floor;ctx.fillRect(0,horizon,w,h-horizon);ctx.strokeStyle='#12bbd733';for(let i=1;i<9;i++){const y=horizon+(h-horizon)*(i*i/64);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
const depth=[],step=2,projection=w/(2*Math.tan(FOV/2));for(let x=0;x<w;x+=step){const offset=Math.atan((x-w/2)/projection),a=p.a+offset,d=E.ray(p.x,p.y,a)*Math.cos(offset);depth[x/step]=d;const height=Math.min(h*3,projection/Math.max(.1,d)),top=horizon-height/2,hitX=p.x+Math.cos(a)*d/Math.cos(offset),hitY=p.y+Math.sin(a)*d/Math.cos(offset),fx=Math.min(hitX%1,1-hitX%1),fy=Math.min(hitY%1,1-hitY%1),edge=fx<fy?fy:fx;const brightness=Math.max(14,58-d*4);ctx.fillStyle=`hsl(223,55%,${brightness}%)`;ctx.fillRect(x,top,step,height);ctx.fillStyle=edge<.035?'#36d7ff':'#3683a8';ctx.fillRect(x,top,step,Math.max(1,3/d));ctx.fillRect(x,top+height,step,Math.max(1,3/d));if(edge<.03){ctx.globalAlpha=.7;ctx.fillRect(x,top,step,height);ctx.globalAlpha=1}ctx.fillStyle='#62ceff44';ctx.fillRect(x,horizon,step,Math.max(1,1/d))}
const sprites=[...state.enemies.map(e=>({...e,kind:'robot'})),...state.shots.map(s=>({...s,kind:'shot'})),...state.pickups.map(i=>({...i,kind:'pickup'}))].map(s=>({...s,d:Math.hypot(s.x-p.x,s.y-p.y),offset:E.angle(Math.atan2(s.y-p.y,s.x-p.x)-p.a)})).sort((a,b)=>b.d-a.d);
for(const s of sprites){if(Math.abs(s.offset)>FOV*.8||s.d<.12)continue;const z=s.d*Math.cos(s.offset),sx=w/2+Math.tan(s.offset)*projection,size=Math.min(h*2,projection/z*(s.kind==='robot'?.75:.2)),top=horizon-size*.5+(s.kind==='pickup'?size*1.7:0);const color=s.kind==='shot'?'#ff5ba9':s.kind==='pickup'?(s.type==='health'?'#5bffaa':s.type==='shield'?'#5baaff':'#ffdf6b'):s.hit?'#fff':s.type==='tank'?'#b68bff':s.type==='sentry'?'#ff6cc8':'#50ddff';
// Clip each sprite to wall-visible columns, so robots and projectiles cannot show through cover.
ctx.save();ctx.beginPath();for(let x=Math.max(0,Math.floor((sx-size*.5)/step)*step);x<Math.min(w,sx+size*.5);x+=step)if(z<depth[Math.floor(x/step)]+.05)ctx.rect(x,0,step,h);ctx.clip();ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=8;
if(s.kind!=='robot'){ctx.beginPath();ctx.arc(sx,top+size/2,size/2,0,Math.PI*2);ctx.fill();if(s.kind==='pickup'){ctx.shadowBlur=0;ctx.fillStyle='#07162a';ctx.font=`bold ${Math.max(8,size*.65)}px system-ui`;ctx.textAlign='center';ctx.fillText(s.type==='health'?'+':s.type==='shield'?'S':'⚡',sx,top+size*.75)}}else{const bodyY=top+size*.35;ctx.fillRect(sx-size*.27,top,size*.54,size*.29);ctx.fillRect(sx-size*.32,bodyY,size*.64,size*.4);ctx.fillRect(sx-size*.46,bodyY,size*.12,size*.4);ctx.fillRect(sx+size*.34,bodyY,size*.12,size*.4);ctx.fillRect(sx-size*.28,top+size*.79,size*.2,size*.21);ctx.fillRect(sx+size*.08,top+size*.79,size*.2,size*.21);ctx.shadowBlur=0;ctx.fillStyle='#061326';ctx.fillRect(sx-size*.2,top+size*.1,size*.4,size*.075);ctx.fillStyle=s.type==='sentry'&&s.attack<.65?'#fff17b':'#ffffff';ctx.fillRect(sx-size*.12,top+size*.11,size*.075,size*.045);ctx.fillRect(sx+size*.05,top+size*.11,size*.075,size*.045);ctx.fillStyle='#092442';ctx.fillRect(sx-size*.1,bodyY+size*.1,size*.2,size*.17)}ctx.restore()}
ctx.textAlign='left';ctx.shadowBlur=0;ctx.strokeStyle=state.flash>0?'#fff17b':'#c7f8ff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(w/2-12,horizon);ctx.lineTo(w/2-4,horizon);ctx.moveTo(w/2+4,horizon);ctx.lineTo(w/2+12,horizon);ctx.moveTo(w/2,horizon-12);ctx.lineTo(w/2,horizon-4);ctx.moveTo(w/2,horizon+4);ctx.lineTo(w/2,horizon+12);ctx.stroke();
const recoil=state.flash>0?10:0;ctx.fillStyle='#182641';ctx.beginPath();ctx.moveTo(w*.4,h);ctx.lineTo(w*.45,h-65+recoil);ctx.lineTo(w*.48,h-90+recoil);ctx.lineTo(w*.55,h-90+recoil);ctx.lineTo(w*.59,h);ctx.fill();ctx.fillStyle='#30dbff';ctx.fillRect(w*.48,h-85+recoil,w*.07,8);ctx.fillStyle='#a43b9a';ctx.fillRect(w*.48,h-60+recoil,w*.06,34);if(state.flash>0){ctx.fillStyle='#fff493';ctx.beginPath();ctx.arc(w*.515,h-100+recoil,17,0,Math.PI*2);ctx.fill()}
ctx.fillStyle='#e0faff';ctx.font='bold 12px system-ui';ctx.fillText(`WAVE ${Math.max(1,state.wave)} · ${Math.ceil(180-state.time)}s`,12,23);if(!state.enemies.length&&running){ctx.textAlign='center';ctx.fillStyle='#72efff';ctx.fillText('NEXT WAVE INCOMING',w/2,55);ctx.textAlign='left'}if(state.shield>0||state.overdrive>0){ctx.fillStyle='#ffdc79';ctx.fillText(state.shield>0?'SHIELD ACTIVE':'RAPID FIRE',12,43)}if(state.hurt>0){ctx.fillStyle=`rgba(255,40,95,${state.hurt*.5})`;ctx.fillRect(0,0,w,h)}
}
function loop(now){if(!running||paused)return;const dt=Math.min(.05,(now-last)/1000);last=now;const input={forward:joy.forward+(keys.has('w')||keys.has('ArrowUp')?1:0)-(keys.has('s')||keys.has('ArrowDown')?1:0),strafe:joy.strafe+(keys.has('d')?1:0)-(keys.has('a')?1:0),turn:(keys.has('ArrowRight')?2:0)-(keys.has('ArrowLeft')?2:0),fire:fireId!==null||keys.has(' ')};E.tick(state,dt,input);chrome();render();if(state.ended){finish();return}raf=requestAnimationFrame(loop)}
function finish(){if(!running)return;running=false;resetInput();cancelAnimationFrame(raf);status('Run Over',false);els.startButton.textContent='▶ PLAY AGAIN';message.hidden=false;message.innerHTML='RUN COMPLETE<span>Ready for another breach?</span>';const coins=Math.min(25,Math.floor(state.score/150));Arcade.earn(coins,'Neon Breach',{kind:'game',game,metric:state.score,aux:state.kills});const result=Arcade.recordResult(game,state.score);chrome();Arcade.gameResult({game,icon:'🤖',title:'Neon Breach Run Over',scoreLabel:'POINTS',score:state.score,best:Arcade.best(game).display,coins,result,playsLeft:Arcade.remaining(game),extra:[`🤖 Robots defeated: ${state.kills}`,`⚡ Wave reached: ${state.wave}`,`⏱️ Time played: ${Math.round(state.time)}s`],onReplay:start,onMorePlays:()=>Arcade.out(game,chrome)})}
function start(){if(running||starting)return;if(!Arcade.consume(game)){Arcade.out(game,chrome);return}starting=true;els.startButton.disabled=true;resetInput();state=E.create();message.hidden=true;render();Arcade.countdown(()=>{starting=false;running=true;paused=false;els.startButton.disabled=false;status('Running',true);chrome();last=performance.now();raf=requestAnimationFrame(loop)})}
els.startButton.addEventListener('click',start);
function capture(el,e){e.preventDefault();el.setPointerCapture(e.pointerId)}
pad.addEventListener('pointerdown',e=>{if(!running||paused||moveId!==null)return;moveId=e.pointerId;capture(pad,e);steer(e)});function steer(e){const r=pad.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/32,dy=(e.clientY-r.top-r.height/2)/32,n=Math.max(1,Math.hypot(dx,dy));joy={strafe:dx/n,forward:-dy/n};knob.style.transform=`translate(${joy.strafe*28}px,${-joy.forward*28}px)`}pad.addEventListener('pointermove',e=>{if(e.pointerId===moveId){e.preventDefault();steer(e)}});
canvas.addEventListener('pointerdown',e=>{if(!running||paused||aimId!==null)return;aimId=e.pointerId;aimX=e.clientX;capture(canvas,e)});canvas.addEventListener('pointermove',e=>{if(e.pointerId===aimId&&running&&!paused){e.preventDefault();state.player.a=E.angle(state.player.a+(e.clientX-aimX)*.008);aimX=e.clientX}});
fireButton.addEventListener('pointerdown',e=>{if(!running||paused||fireId!==null)return;fireId=e.pointerId;capture(fireButton,e)});
function release(e){if(e.pointerId===moveId){moveId=null;joy={forward:0,strafe:0};knob.style.transform=''}if(e.pointerId===aimId)aimId=null;if(e.pointerId===fireId)fireId=null}for(const name of ['pointerup','pointercancel','lostpointercapture'])document.addEventListener(name,release);
document.addEventListener('keydown',e=>{if(e.target.closest?.('input,textarea,a,.modal-backdrop'))return;if(['w','a','s','d',' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();if(running&&!paused)keys.add(e.key)}if(e.key==='Enter'&&!running&&!starting)start()});document.addEventListener('keyup',e=>keys.delete(e.key));
pauseControl=Arcade.installPauseControl({isRunning:()=>running,pause:()=>{paused=true;resetInput();cancelAnimationFrame(raf);message.innerHTML='PAUSED<span>Tap a control to resume</span>';message.hidden=false},resume:()=>{if(!paused||!running)return;paused=false;message.hidden=true;resetInput();last=performance.now();raf=requestAnimationFrame(loop)},resumeOnInput:e=>e.type==='keydown'||!!e.target.closest?.('#breachControls,#game')});
// Shared mobile dock is initially inserted after the canvas; move it below the thumb controls.
let dock=document.querySelector('.earnly-session-dock');if(!dock){dock=document.createElement('div');dock.className='earnly-session-dock';dock.append(pauseControl.button,document.getElementById('earnlyQuitButton'))}document.getElementById('breachControls').insertAdjacentElement('afterend',dock);
function backgroundPause(){resetInput();if(running&&!paused)pauseControl.button.click()}window.addEventListener('blur',backgroundPause);document.addEventListener('visibilitychange',()=>{if(document.hidden)backgroundPause()});window.addEventListener('pagehide',()=>{running=false;starting=false;cancelAnimationFrame(raf);resetInput()});
new ResizeObserver(()=>{const r=canvas.getBoundingClientRect();canvas.height=Math.round(400*r.height/Math.max(1,r.width));render()}).observe(canvas);chrome();render();
})();
