const {test,expect}=require('@playwright/test');
const E=require('../crystal-command-engine');
function advance(s,seconds){for(let i=0;i<Math.round(seconds/E.STEP)&&!s.ended;i++)E.tick(s)}
test('workers deliver finite crystals and two armies start hidden',()=>{const s=E.create();expect(s.entities.filter(e=>e.side===0&&e.type==='worker')).toHaveLength(4);expect(E.view(s,0).entities.some(e=>e.side===1)).toBe(false);const total=s.crystals.reduce((n,c)=>n+c.left,0);advance(s,20);expect(s.players[0].mined).toBeGreaterThan(0);expect(s.crystals.reduce((n,c)=>n+c.left,0)+s.entities.reduce((n,e)=>n+e.carry,0)+s.players.reduce((n,p)=>n+p.mined,0)).toBe(total)});
test('construction, unit prerequisites and supply prevent button-spam armies',()=>{const s=E.create();const base=s.entities.find(e=>e.side===0&&e.type==='base');expect(E.command(s,0,{type:'train',id:base.id,kind:'siege'}).ok).toBe(false);expect(E.command(s,0,{type:'build',kind:'factory',x:9,y:6}).ok).toBe(true);expect(E.command(s,0,{type:'build',kind:'factory',x:9,y:6}).ok).toBe(false);const f=s.entities.find(e=>e.side===0&&e.type==='factory');expect(E.command(s,0,{type:'train',id:f.id,kind:'laser'}).ok).toBe(false);advance(s,12);s.players[0].crystals=10000;expect(E.command(s,0,{type:'train',id:f.id,kind:'siege'}).ok).toBe(false);for(let i=0;i<20;i++)E.command(s,0,{type:'train',id:f.id,kind:'laser'});expect(f.queue.length).toBe(5);advance(s,40);for(let i=0;i<20;i++)E.command(s,0,{type:'train',id:f.id,kind:'laser'});expect(E.supply(s,0).used).toBeLessThanOrEqual(16)});
test('orders validate owner, fog, coordinates and payload size',()=>{const s=E.create();const enemy=s.entities.find(e=>e.side===1&&e.type==='worker');expect(E.command(s,0,{type:'move',ids:[enemy.id],x:10,y:10}).ok).toBe(false);expect(E.command(s,0,{type:'build',kind:'base',x:33,y:33}).ok).toBe(false);expect(E.command(s,0,{type:'move',ids:Array(100).fill(1),x:NaN,y:1}).ok).toBe(false);expect(E.command(s,0,{type:'train',id:1,kind:'toString'}).ok).toBe(false);expect(E.command(s,0,{type:'build',kind:'toString',x:9,y:6}).ok).toBe(false);expect(Number.isFinite(s.players[0].crystals)).toBe(true)});
test('scouting reveals units and attack-move can destroy a rival base',()=>{const s=E.create();const army=s.entities.find(e=>e.side===0&&e.type==='worker');army.type='siege';army.hp=250;army.x=31;army.y=31;advance(s,.1);expect(E.view(s,0).entities.some(e=>e.side===1)).toBe(true);E.command(s,0,{type:'attack',ids:[army.id],x:33,y:33});advance(s,130);expect(s.ended).toBe(true);expect(s.winner).toBe(0)});
test('mining and combat produce deterministic state and idle practice loses',()=>{const a=E.create({practice:true}),b=E.create({practice:true});advance(a,140);advance(b,140);expect(E.view(a,0)).toEqual(E.view(b,0));expect(a.ended).toBe(true);expect(a.winner).toBe(1);expect(a.time).toBeLessThan(140)});
test('tactical paths avoid rocks and exhausted crystals cannot mint income',()=>{const s=E.create();const p=E.path(s,{x:10,y:12},{x:14,y:12});expect(p.length).toBeGreaterThan(4);expect(p.some(t=>s.rocks.some(r=>r.x===Math.floor(t.x)&&r.y===Math.floor(t.y)))).toBe(false);s.crystals.forEach(n=>n.left=0);advance(s,10);expect(s.players[0].crystals).toBe(250)});
test('mobile strategy controls, pause and quit confirmation work',async({page})=>{
 await page.goto('/crystal-command.html');await page.getByRole('button',{name:'▶ Practice battle'}).click();await expect(page.locator('#lobby')).toBeHidden();await expect(page.locator('.public-footer')).toBeHidden();await expect(page.locator('#crystals')).not.toHaveText('250',{timeout:15000});await page.getByRole('button',{name:'Build',exact:true}).click();await page.locator('#palette').getByRole('button',{name:/War factory/}).click();await expect(page.locator('#context')).toContainText('Place War factory');await expect(page.locator('[data-kind=factory]')).toHaveAttribute('aria-pressed','true');await page.locator('#pause').click();const tick=await page.evaluate(()=>CrystalGame.view.tick);await page.waitForTimeout(300);expect(await page.evaluate(()=>CrystalGame.view.tick)).toBe(tick);await page.locator('#pause').click();await page.locator('#quit').click();await expect(page.locator('#confirm')).toBeVisible();await page.getByRole('button',{name:'Keep playing'}).click();await expect(page.locator('#confirm')).toBeHidden();expect(await page.evaluate(()=>CrystalGame.running)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/crystal-command-${test.info().project.name}.png`});await page.locator('#quit').click();await page.getByRole('button',{name:'Quit battle',exact:true}).click();await expect(page.locator('#results')).toBeVisible();await expect(page.locator('#resultStats > div')).toHaveCount(3);await expect(page.locator('.public-footer')).toBeVisible();
});
test('friend rooms show a useful sign-in requirement to guests',async({page})=>{await page.goto('/crystal-command.html');await page.locator('#createRoom').click();await expect(page.locator('#lobbyError')).toContainText('Sign in');await expect(page.locator('#authLink')).toBeVisible()});

test('polished command deck fits small phones and rendered factories remain selectable',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.addInitScript(()=>localStorage.setItem('crystalSound','off'));
 await page.setViewportSize({width:320,height:568});await page.goto('/crystal-command.html');
 await expect(page.locator('.cc-dock')).toBeHidden();await expect(page.locator('#authLink')).toBeHidden();
 await page.getByRole('button',{name:'▶ Practice battle'}).click();
 await page.getByRole('button',{name:'Build',exact:true}).click();
 await expect(page.locator('#palette [data-kind=factory]')).toBeVisible();for(const box of await page.locator('#palette button').evaluateAll(buttons=>buttons.map(button=>{const r=button.getBoundingClientRect();return{x:r.x,width:r.width}}))){expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(320)}
 const quit=await page.locator('#quit').boundingBox();expect(quit.y+quit.height).toBeLessThanOrEqual(568);
 await page.locator('#pause').click();
 const at=await page.evaluate(()=>{const s=CrystalGame.state;s.players[0].crystals=1000;const result=CrystalCommand.command(s,0,{type:'build',kind:'factory',x:9,y:6});if(!result.ok)throw Error(result.message);for(let i=0;i<210;i++)CrystalCommand.tick(s);return s.tick});
 await page.locator('#pause').click();await page.waitForFunction(tick=>CrystalGame.view.tick>tick,at);
 const scale=await page.evaluate(()=>CrystalGame.renderer.point(10,6).x-CrystalGame.renderer.point(9,6).x);await page.getByRole('button',{name:'Zoom in',exact:true}).click();await expect.poll(()=>page.evaluate(()=>CrystalGame.renderer.point(10,6).x-CrystalGame.renderer.point(9,6).x)).toBeGreaterThan(scale);
 const target=await page.evaluate(()=>CrystalGame.renderer.point(9,6,.4));
 expect(await page.evaluate(p=>CrystalGame.renderer.minimap(p.x,p.y),target)).toBe(false);
 await page.locator('#battle').click({position:target});
 await expect(page.locator('#context')).toContainText('War factory selected');await expect(page.locator('#palette')).toContainText('Striker');await expect(page.locator('#selectionName')).toHaveText('War factory');await expect(page.locator('#palette svg')).toHaveCount(3);
 await page.locator('#palette').getByRole('button',{name:/Striker/}).click();await expect(page.locator('#context')).toContainText('queued');
 expect(errors).toEqual([]);
});

test('expanded mineral lines last through an established economy and remain mirrored',()=>{
 const s=E.create(),home=s.crystals.filter(n=>n.field==='Home field 0');expect(home).toHaveLength(6);expect(home.reduce((sum,n)=>sum+n.left,0)).toBe(14400);
 for(const n of s.crystals)expect(s.crystals.some(m=>m.x===39-n.x&&m.y===39-n.y&&m.left===n.left&&m.rich===n.rich)).toBe(true);
 const worker=s.entities.find(e=>e.type==='worker'&&e.side===0);for(let i=0;i<8;i++)s.entities.push({...worker,id:s.next++,x:5+i%3*.2,y:8+Math.floor(i/3)*.2,path:[],queue:[]});
 const total=s.crystals.reduce((sum,n)=>sum+n.left,0);advance(s,300);expect(home.reduce((sum,n)=>sum+n.left,0)).toBeGreaterThan(6000);expect(new Set(s.entities.filter(e=>e.side===0&&e.type==='worker').map(e=>e.patch)).size).toBe(6);
 expect(s.crystals.reduce((n,c)=>n+c.left,0)+s.entities.reduce((n,e)=>n+e.carry,0)+s.players.reduce((n,p)=>n+p.mined,0)).toBe(total);
});
test('one patch saturates and unseen reserves retain their last observed amount',()=>{
 const s=E.create(),node=s.crystals.find(n=>n.field==='Home field 0'),worker=s.entities.find(e=>e.type==='worker'&&e.side===0);s.crystals.forEach(n=>n.left=n.id===node.id?2400:0);s.entities=s.entities.filter(e=>e.type!=='worker');
 for(let i=0;i<12;i++)s.entities.push({...worker,id:s.next++,x:node.x+.1,y:node.y+.1,patch:node.id,path:[],queue:[],order:{type:'mine',x:node.x,y:node.y,target:node.id}});
 advance(s,12);expect(2400-node.left).toBeGreaterThan(0);expect(2400-node.left).toBeLessThanOrEqual(56);
 const observed=E.view(s,0).crystals.find(n=>n.id===node.id).left;s.entities.filter(e=>e.side===0).forEach(e=>{e.x=20;e.y=35;e.path=[];e.order={type:'stop'}});node.left=123;advance(s,.1);
 expect(E.view(s,0).crystals.find(n=>n.id===node.id).left).toBe(observed);
 s.entities.find(e=>e.side===0&&e.type==='base').x=node.x;s.entities.find(e=>e.side===0&&e.type==='base').y=node.y;advance(s,.1);expect(E.view(s,0).crystals.find(n=>n.id===node.id).left).toBe(123);
});
test('rally orders route new Miners to fields and only accept owned production buildings',()=>{
 const s=E.create(),base=s.entities.find(e=>e.side===0&&e.type==='base'),enemy=s.entities.find(e=>e.side===1&&e.type==='base'),node=s.crystals.find(n=>n.field==='Home field 0');
 expect(E.command(s,0,{type:'rally',id:enemy.id,x:3,y:3}).ok).toBe(false);expect(E.command(s,0,{type:'rally',id:base.id,x:NaN,y:3}).ok).toBe(false);
 expect(E.command(s,0,{type:'rally',id:base.id,x:node.x,y:node.y,target:node.id}).ok).toBe(true);const last=s.next;expect(E.command(s,0,{type:'train',id:base.id,kind:'worker'}).ok).toBe(true);advance(s,4.1);
 expect(s.entities.find(e=>e.id===last).order.target).toBe(node.id);
 expect(E.view(s,1).entities.filter(e=>e.side===0).every(e=>e.rally===null)).toBe(true);
});
test('research takes time, blocks duplicate projects and cancels with its Tech core',()=>{
 const s=E.create();s.players[0].crystals=3000;expect(E.command(s,0,{type:'build',kind:'lab',x:9,y:10}).ok).toBe(true);advance(s,12.1);const lab=s.entities.find(e=>e.type==='lab');
 expect(E.command(s,0,{type:'upgrade',id:lab.id,kind:'weapons'}).ok).toBe(true);expect(s.players[0].upgrade).toBe(0);const paid=s.players[0].crystals;
 expect(E.command(s,0,{type:'upgrade',id:lab.id,kind:'weapons'}).ok).toBe(false);expect(s.players[0].crystals).toBe(paid);advance(s,17);expect(s.players[0].upgrade).toBe(0);advance(s,1.1);expect(s.players[0].upgrade).toBe(1);
 expect(E.command(s,0,{type:'upgrade',id:lab.id,kind:'armor'}).ok).toBe(true);advance(s,16.1);expect(s.players[0].armor).toBe(1);
 expect(E.command(s,0,{type:'upgrade',id:lab.id,kind:'armor'}).ok).toBe(true);lab.hp=0;advance(s,30);expect(s.players[0].armor).toBe(1);
 const quiet=E.create();advance(quiet,600);expect(quiet.ended).toBe(false);advance(quiet,601);expect(quiet.reason).toContain('Twenty-minute');
});
test('phone economy controls inspect reserves, set rallies and show timed research',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('crystalSound','off'));await page.setViewportSize({width:320,height:568});await page.goto('/crystal-command.html');await page.locator('#practice').click();
 await expect(page.locator('#selectionDetail')).toContainText('crystals nearby');await page.evaluate(()=>CrystalGame.issue({type:'stop',ids:CrystalGame.view.entities.filter(e=>e.side===0&&e.type==='worker').map(e=>e.id)}));await page.locator('#setRally').click();const node=await page.evaluate(()=>{const n=CrystalGame.view.crystals.find(n=>n.field==='Home field 0');return{id:n.id,p:CrystalGame.renderer.point(n.x,n.y,.5)}});await page.locator('#battle').click({position:node.p});
 expect(await page.evaluate(()=>CrystalGame.state.entities.find(e=>e.type==='base'&&e.side===0).rally.target)).toBe(node.id);await expect(page.locator('#setRally')).toHaveAttribute('aria-pressed','false');
 await page.locator('#battle').click({position:node.p});await expect(page.locator('#selectionName')).toHaveText('Crystal patch');await expect(page.locator('#selectionDetail')).toContainText('remaining');
 await page.locator('#pause').click();const tick=await page.evaluate(()=>{const s=CrystalGame.state;s.players[0].crystals=3000;const r=CrystalCommand.command(s,0,{type:'build',kind:'lab',x:9,y:10});if(!r.ok)throw Error(r.message);for(let i=0;i<245;i++)CrystalCommand.tick(s);return s.tick});await page.locator('#pause').click();await page.waitForFunction(t=>CrystalGame.view.tick>t,tick);await page.evaluate(()=>CrystalGame.renderer.center(9,10));
 await expect.poll(()=>page.evaluate(()=>{const p=CrystalGame.renderer.point(9,10,.4),r=document.getElementById('battle').getBoundingClientRect();return Math.abs(p.x-r.width/2)})).toBe(0);
 const at=await page.evaluate(()=>CrystalGame.renderer.point(9,10,.4));await page.locator('#battle').click({position:at});await expect(page.locator('#palette')).toContainText('Weapons 1');await expect(page.locator('#palette')).toContainText('Armor 1');await page.locator('[data-research=weapons]').click();await expect(page.locator('#selectionDetail')).toContainText('Research');expect(await page.evaluate(()=>CrystalGame.view.player.upgrade)).toBe(0);await expect(page.locator('[data-research=weapons]')).toBeDisabled();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const quit=await page.locator('#quit').boundingBox();expect(quit.y+quit.height).toBeLessThanOrEqual(568);expect(errors).toEqual([]);
});

test('practice difficulty changes opening pressure without changing player resources',()=>{
 const attacks={};for(const difficulty of ['easy','normal','hard']){const s=E.create({practice:true,difficulty});expect(s.players[0].crystals).toBe(250);expect(s.crystals.filter(n=>n.field==='Home field 0').reduce((n,c)=>n+c.left,0)).toBe(14400);for(let i=0;i<4100;i++){E.tick(s);if(s.entities.some(e=>e.side===1&&e.order?.type==='attack')){attacks[difficulty]=s.time;break}}expect(attacks[difficulty]).toBeGreaterThan(0)}expect(attacks.easy).toBeGreaterThanOrEqual(180);expect(attacks.hard).toBeLessThan(attacks.normal);expect(attacks.normal).toBeLessThan(attacks.easy);expect(E.create({difficulty:'toString'}).difficulty).toBe('normal');expect(E.view(E.create(),0).difficulty).toBe(null);
});
test('focus fire validates visibility and pursues only the last known enemy position',()=>{
 const s=E.create(),a=s.entities.find(e=>e.side===0&&e.type==='worker'),enemy=s.entities.find(e=>e.side===1&&e.type==='base');a.type='laser';a.x=29;a.y=33;a.order={type:'stop'};advance(s,.1);
 expect(E.command(s,0,{type:'attack',ids:[a.id],x:a.x,y:a.y,target:a.id}).ok).toBe(false);expect(E.command(s,0,{type:'attack',ids:[a.id],x:enemy.x,y:enemy.y,target:enemy.id}).ok).toBe(true);
 const prior=enemy.hp;advance(s,1);expect(enemy.hp).toBeLessThan(prior);expect(E.view(s,1).player.alerts.base.tick).toBeGreaterThan(0);expect(E.view(s,0).player.alerts.base).toBeUndefined();const known={x:a.order.x,y:a.order.y};enemy.x=5;enemy.y=35;advance(s,.1);expect(a.order.x).toBe(known.x);expect(a.order.y).toBe(known.y);expect(E.command(s,0,{type:'attack',ids:[a.id],x:enemy.x,y:enemy.y,target:enemy.id}).ok).toBe(false);
});
test('phone squads save survivors, select multiple fighters and issue visible enemy targets',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('crystalSound','off'));await page.setViewportSize({width:320,height:568});await page.goto('/crystal-command.html');await expect(page.getByRole('radio',{name:/Easy/})).toHaveAttribute('aria-checked','true');await page.getByRole('radio',{name:/Hard/}).click();await page.locator('#practice').click();expect(await page.evaluate(()=>CrystalGame.state.difficulty)).toBe('hard');await page.locator('#pause').click();
 const harness=await page.evaluate(()=>{const s=CrystalGame.state;const workers=s.entities.filter(e=>e.side===0&&e.type==='worker');workers.slice(0,2).forEach((e,i)=>{e.type='laser';e.x=8+i*2;e.y=8;e.hp=e.maxHp=120;e.order={type:'stop'}});const enemy=s.entities.find(e=>e.side===1&&e.type==='worker');enemy.x=11;enemy.y=10;enemy.hp=enemy.maxHp=100000;enemy.order={type:'stop'};CrystalCommand.tick(s);return{tick:s.tick,ids:workers.slice(0,2).map(e=>e.id),enemy:enemy.id}});await page.locator('#pause').click();await page.waitForFunction(t=>CrystalGame.view.tick>t,harness.tick);await page.evaluate(()=>CrystalGame.renderer.center(9,8));await page.locator('#selectArmy').click();await expect(page.locator('#palette')).toHaveAttribute('data-mode','army');await page.locator('[data-save="0"]').click();await expect(page.locator('[data-recall="0"]')).toContainText('2');await page.keyboard.press('Shift+Digit2');await expect(page.locator('[data-recall="1"]')).toContainText('2');await page.keyboard.press('Digit2');await expect(page.locator('#selectionName')).toHaveText('2 units');await page.locator('[data-multi]').click();await expect(page.locator('[data-multi]')).toHaveAttribute('aria-pressed','true');
 const p=await page.evaluate(id=>{const e=CrystalGame.view.entities.find(e=>e.id===id);return CrystalGame.renderer.point(e.x,e.y,.4)},harness.ids[1]);await page.locator('#battle').click({position:p});await expect(page.locator('#selectionName')).toHaveText('Striker');await page.locator('[data-save="1"]').click();await expect(page.locator('[data-recall="1"]')).toContainText('1');await page.locator('[data-recall="0"]').click();await expect(page.locator('#selectionName')).toHaveText('2 units');
 const target=await page.evaluate(id=>{const e=CrystalGame.view.entities.find(e=>e.id===id);return CrystalGame.renderer.point(e.x,e.y,.4)},harness.enemy);await page.locator('#battle').click({position:target});expect(await page.evaluate(ids=>ids.every(id=>CrystalGame.state.entities.find(e=>e.id===id).order.target!==undefined),harness.ids)).toBe(true);await page.locator('[data-stop]').click();expect(await page.evaluate(ids=>ids.every(id=>CrystalGame.state.entities.find(e=>e.id===id).order.type==='stop'),harness.ids)).toBe(true);
 await page.locator('#pause').click();const death=await page.evaluate(id=>{CrystalGame.state.entities.find(e=>e.id===id).hp=0;CrystalCommand.tick(CrystalGame.state);return CrystalGame.state.tick},harness.ids[1]);await page.locator('#pause').click();await page.waitForFunction(t=>CrystalGame.view.tick>t,death);await page.locator('[data-recall="0"]').click();await expect(page.locator('#selectionName')).toHaveText('Striker');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const quit=await page.locator('#quit').boundingBox();expect(quit.y+quit.height).toBeLessThanOrEqual(568);expect(errors).toEqual([]);await page.locator('#quit').click();await page.locator('#confirmQuit').click();await page.locator('#again').click();await page.locator('#practice').click();await page.locator('#selectArmy').click();await expect(page.locator('[data-recall="0"]')).toBeDisabled();
});
test('battle alerts locate attacks and do not repeat each render frame',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('crystalSound','off'));await page.goto('/crystal-command.html');await page.locator('#practice').click();await page.locator('#pause').click();const t=await page.evaluate(()=>{const s=CrystalGame.state,base=s.entities.find(e=>e.side===0&&e.type==='base');s.players[0].alerts.base={tick:s.tick,time:s.time,x:base.x,y:base.y};CrystalCommand.tick(s);return s.tick});await page.locator('#pause').click();await page.waitForFunction(tick=>CrystalGame.view.tick>tick,t);await expect(page.locator('#battleAlert')).toContainText('Base under attack');await page.evaluate(()=>CrystalGame.renderer.center(20,20));await page.locator('#battleAlert').click();expect(await page.evaluate(()=>Math.abs(CrystalGame.renderer.point(6,6).x-document.getElementById('battle').getBoundingClientRect().width/2))).toBe(0);await page.waitForTimeout(7000);await expect(page.locator('#battleAlert')).toBeHidden();
});

test('destruction effects respect fog and are emitted once',()=>{
 const s=E.create(),enemy=s.entities.find(e=>e.side===1&&e.type==='worker');enemy.hp=0;E.tick(s);
 expect(s.events.filter(e=>e.type==='destroyed')).toHaveLength(1);expect(E.view(s,0).events.some(e=>e.type==='destroyed')).toBe(false);expect(E.view(s,1).events.some(e=>e.type==='destroyed')).toBe(true);
 E.tick(s);expect(s.events.some(e=>e.type==='destroyed')).toBe(false);expect(E.view(s,1).visualEvents.some(e=>e.type==='destroyed')).toBe(true);expect(E.view(s,0).visualEvents.some(e=>e.type==='destroyed')).toBe(false);advance(s,1);expect(E.view(s,1).visualEvents).toHaveLength(0);
 const own=s.entities.find(e=>e.side===0&&e.type==='worker');own.hp=0;E.tick(s);expect(E.view(s,0).events.find(e=>e.type==='destroyed')).toMatchObject({kind:'worker',x:own.x,y:own.y});
});
test('battlefield art freezes with game time and supports crowded reduced-motion scenes',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/crystal-command.html');
 const result=await page.evaluate(()=>{
  const canvas=document.createElement('canvas');canvas.style.cssText='width:440px;height:500px';document.body.append(canvas);const r=CrystalRenderer.create(canvas),s=CrystalCommand.create(),v=CrystalCommand.view(s,0);v.tick=100;v.time=10;v.visible.fill(1);v.seen.fill(1);
  const sample=v.entities.find(e=>e.type==='worker');for(let i=0;i<120;i++)v.entities.push({...sample,id:1000+i,type:['worker','scout','laser','siege'][i%4],x:2+i%12*.6,y:2+Math.floor(i/12)*.6,hp:15,maxHp:100,carry:i%3?8:0,mine:i%3?0:1,order:{type:'move',x:8,y:8}});
  for(const [type,x,y,build]of [['factory',9,6,0],['lab',9,10,5],['relay',5,9,0],['turret',10,3,0]])v.entities.push({...sample,id:2000+v.entities.length,type,x,y,build,queue:type==='factory'?['laser']:[],progress:4});
  delete v.visualEvents;v.events=[{type:'shot',side:0,x:6,y:6,tx:8,ty:7,kind:'siege'},{type:'destroyed',side:0,x:5,y:5,kind:'laser'}];const before=JSON.stringify(v);r.render(v);const first=canvas.toDataURL();r.render(v);const frozen=canvas.toDataURL()===first;const timings=[];for(let i=0;i<30;i++){const t=performance.now();r.render(v);timings.push(performance.now()-t)}timings.sort((a,b)=>a-b);const unchanged=before===JSON.stringify(v);canvas.remove();return{frozen,unchanged,p95:timings[28]};
 });expect(result.frozen).toBe(true);expect(result.unchanged).toBe(true);expect(errors).toEqual([]);console.log('Crowded battlefield render p95 (ms):',result.p95.toFixed(1));
});

async function boxFixture(page){
 await page.addInitScript(()=>localStorage.setItem('crystalSound','off'));await page.setViewportSize({width:440,height:956});await page.goto('/crystal-command.html');await page.locator('#practice').click();await page.locator('#pause').click();
 const fixture=await page.evaluate(()=>{const s=CrystalGame.state,sample=s.entities.find(e=>e.side===0&&e.type==='worker');s.entities=s.entities.filter(e=>e.type!=='worker');const ids=[];for(const [side,type,x,y]of [[0,'laser',7,7],[0,'siege',8,7],[0,'worker',7,8],[1,'laser',8,8],[0,'laser',12,9]]){const e={...sample,id:s.next++,side,type,x,y,hp:100000,maxHp:100000,carry:0,mine:0,path:[],queue:[],order:{type:'stop'}};s.entities.push(e);ids.push(e.id)}CrystalCommand.tick(s);return{ids,tick:s.tick}});
 await page.locator('#pause').click();await page.waitForFunction(t=>CrystalGame.view.tick>t,fixture.tick);return fixture;
}
async function pointer(page,type,x,y,extra={}){await page.locator('#battle').dispatchEvent(type,{pointerId:91,pointerType:'touch',button:0,buttons:type==='pointerup'?0:1,clientX:x,clientY:y,isPrimary:true,...extra});}
async function touchBox(page,start,end,{double=false,cancel=false}={}){
 await page.evaluate(()=>{const c=document.getElementById('battle'),capture=c.setPointerCapture;c.setPointerCapture=function(id){try{capture.call(this,id)}catch{}}});const b=await page.locator('#battle').boundingBox(),a={x:b.x+start.x,y:b.y+start.y},z={x:b.x+end.x,y:b.y+end.y};if(double){await pointer(page,'pointerdown',a.x,a.y);await pointer(page,'pointerup',a.x,a.y)}await pointer(page,'pointerdown',a.x,a.y);await pointer(page,'pointermove',z.x,z.y);if(cancel)await pointer(page,'pointercancel',z.x,z.y);else await pointer(page,'pointerup',z.x,z.y);
}
test('yellow boxes select owned fighters, support additive groups, miners and cancellation',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));const f=await boxFixture(page);
 // Use screen bounds around the projected unit centers, rather than world-axis corners.
 const area=await page.evaluate(ids=>{const ps=CrystalGame.view.entities.filter(e=>ids.slice(0,4).includes(e.id)).map(e=>CrystalGame.renderer.point(e.x,e.y,.4));return{start:{x:Math.min(...ps.map(p=>p.x))-12,y:Math.min(...ps.map(p=>p.y))-12},end:{x:Math.max(...ps.map(p=>p.x))+12,y:Math.max(...ps.map(p=>p.y))+12}}},f.ids);
 await page.locator('#boxSelect').click();await expect(page.locator('#boxSelect')).toHaveAttribute('aria-pressed','true');
 const b=await page.locator('#battle').boundingBox();await page.mouse.move(b.x+area.start.x,b.y+area.start.y);await page.mouse.down();await page.mouse.move(b.x+area.end.x,b.y+area.end.y,{steps:5});await page.waitForTimeout(70);
 expect(await page.evaluate(()=>!!CrystalGame.selectionBox)).toBe(true);await expect.poll(()=>page.locator('#battle').evaluate((c,box)=>{const r=c.width/c.getBoundingClientRect().width,data=c.getContext('2d').getImageData(Math.floor((box.start.x-2)*r),Math.floor(((box.start.y+box.end.y)/2-2)*r),Math.ceil(5*r),Math.ceil(5*r)).data;for(let i=0;i<data.length;i+=4)if(data[i]>200&&data[i+1]>170&&data[i+2]<160)return true;return false},area)).toBe(true);await page.mouse.up();expect(await page.evaluate(()=>CrystalGame.selection)).toEqual(f.ids.slice(0,2));await expect(page.locator('#boxSelect')).toHaveAttribute('aria-pressed','false');expect(await page.evaluate(ids=>ids.slice(0,3).every(id=>CrystalGame.state.entities.find(e=>e.id===id).order.type==='stop'),f.ids)).toBe(true);
 await page.locator('[data-multi]').click();const extra=await page.evaluate(id=>{const e=CrystalGame.view.entities.find(e=>e.id===id),p=CrystalGame.renderer.point(e.x,e.y,.4);return{start:{x:p.x-10,y:p.y-10},end:{x:p.x+10,y:p.y+10}}},f.ids[4]);await page.locator('#boxSelect').click();await touchBox(page,extra.start,extra.end);expect((await page.evaluate(()=>CrystalGame.selection)).sort()).toEqual([f.ids[0],f.ids[1],f.ids[4]].sort());
 await page.locator('#boxSelect').click();await touchBox(page,area.start,area.end,{cancel:true});expect(await page.evaluate(()=>CrystalGame.selectionBox)).toBeNull();expect((await page.evaluate(()=>CrystalGame.selection)).sort()).toEqual([f.ids[0],f.ids[1],f.ids[4]].sort());
 const worker=await page.evaluate(id=>{const e=CrystalGame.view.entities.find(e=>e.id===id),p=CrystalGame.renderer.point(e.x,e.y,.4);return{start:{x:p.x-5,y:p.y-5},end:{x:p.x+5,y:p.y+5}}},f.ids[2]);await touchBox(page,worker.start,worker.end);expect(await page.evaluate(()=>CrystalGame.selection)).toEqual([f.ids[2]]);
 await page.locator('#boxSelect').click();await touchBox(page,{x:20,y:150},{x:45,y:180});expect(await page.evaluate(()=>CrystalGame.selection)).toEqual([]);expect(errors).toEqual([]);
});
test('phone double-tap drag selects without ordering and ordinary drags still pan',async({page})=>{
 const f=await boxFixture(page);await page.locator('#selectArmy').click();const area=await page.evaluate(ids=>{const ps=CrystalGame.view.entities.filter(e=>ids.slice(0,2).includes(e.id)).map(e=>CrystalGame.renderer.point(e.x,e.y,.4));return{start:{x:Math.min(...ps.map(p=>p.x))-28,y:Math.min(...ps.map(p=>p.y))-28},end:{x:Math.max(...ps.map(p=>p.x))+12,y:Math.max(...ps.map(p=>p.y))+12}}},f.ids);
 await touchBox(page,area.start,area.end,{double:true});expect(await page.evaluate(()=>CrystalGame.selection)).toEqual(f.ids.slice(0,2));await page.waitForTimeout(350);expect(await page.evaluate(ids=>ids.slice(0,2).every(id=>CrystalGame.state.entities.find(e=>e.id===id).order.type==='stop'),f.ids)).toBe(true);
 const before=await page.evaluate(()=>CrystalGame.renderer.point(6,6).x);await touchBox(page,{x:30,y:160},{x:90,y:190});expect(await page.evaluate(()=>CrystalGame.renderer.point(6,6).x)).not.toBe(before);expect(await page.evaluate(()=>CrystalGame.selection)).toEqual(f.ids.slice(0,2));
});
test('radar taps command all troops, drags look around, and large groups use bounded orders',async({page})=>{
 const f=await boxFixture(page);await page.locator('#selectArmy').click();const mini=await page.evaluate(()=>CrystalGame.renderer.minimapBounds),target={x:mini.x+mini.w*.8,y:mini.y+mini.h*.75};await page.locator('#battle').click({position:target});expect(await page.evaluate(ids=>ids.filter((id,i)=>i<2||i===4).every(id=>CrystalGame.state.entities.find(e=>e.id===id).order.type==='attack'),f.ids)).toBe(true);expect(await page.evaluate(ids=>CrystalGame.state.entities.find(e=>e.id===ids[2]).order.type,f.ids)).toBe('stop');
 await page.locator('#orderMode').click();await page.locator('#battle').click({position:{x:mini.x+mini.w*.6,y:mini.y+mini.h*.5}});expect(await page.evaluate(ids=>ids.slice(0,2).every(id=>CrystalGame.state.entities.find(e=>e.id===id).order.type==='move'),f.ids)).toBe(true);const orders=await page.evaluate(()=>JSON.stringify(CrystalGame.state.entities.filter(e=>e.side===0&&e.type!=='base').map(e=>e.order)));await touchBox(page,{x:mini.x+10,y:mini.y+10},{x:mini.x+30,y:mini.y+30});expect(await page.evaluate(()=>JSON.stringify(CrystalGame.state.entities.filter(e=>e.side===0&&e.type!=='base').map(e=>e.order)))).toBe(orders);
 await page.locator('#pause').click();const t=await page.evaluate(()=>{const s=CrystalGame.state,sample=s.entities.find(e=>e.type==='laser'&&e.side===0);for(let i=0;i<90;i++)s.entities.push({...sample,id:s.next++,x:6,y:6,order:{type:'stop'},path:[],queue:[]});CrystalCommand.tick(s);return s.tick});await page.locator('#pause').click();await page.waitForFunction(tick=>CrystalGame.view.tick>tick,t);await page.locator('#selectArmy').click();await page.locator('#battle').click({position:target});expect(await page.evaluate(()=>CrystalGame.state.entities.filter(e=>e.side===0&&e.type==='laser').every(e=>e.order.type==='move'))).toBe(true);
 await page.locator('#home').click();await page.locator('#setRally').click();await page.locator('#battle').click({position:target});expect(await page.evaluate(()=>CrystalGame.state.entities.find(e=>e.side===0&&e.type==='base').rally.x)).toBeCloseTo(32,0);await page.locator('#home').click();const now=await page.evaluate(()=>CrystalGame.renderer.minimapBounds);await page.locator('#battle').click({position:{x:now.x+now.w*.5,y:now.y+now.h*.5}});expect(await page.evaluate(()=>Math.abs(CrystalGame.renderer.point(20,20).x-220))).toBeLessThan(7);
});

test('placement preview agrees with build validation and never mutates a fog-filtered view',()=>{
 const s=E.create(),before=JSON.stringify(s),v=E.view(s,0),viewBefore=JSON.stringify(v);
 for(const [kind,x,y]of [['factory',9,6],['factory',6,6],['relay',3,3],['turret',12,12],['lab',33,33],['factory',NaN,6],['worker',9,6]]){
  const site=E.placement(v,0,kind,x,y),full=E.placement(s,0,kind,x,y);expect(site.ok).toBe(full.ok);expect(site.message).toBe(full.message);
 }
 expect(JSON.stringify(s)).toBe(before);expect(JSON.stringify(v)).toBe(viewBefore);expect(E.placement(v,0,'factory',9,6).ok).toBe(true);
 v.player.crystals=0;expect(E.placement(v,0,'factory',9,6).message).toContain('crystals');v.player.crystals=1000;v.entities=v.entities.filter(e=>e.type!=='worker');expect(E.placement(v,0,'factory',9,6).message).toContain('Miner');
 const result=E.command(s,0,{type:'build',kind:'factory',x:9,y:6});expect(result.ok).toBe(true);expect(s.players[0].crystals).toBe(70);expect(E.placement(E.view(s,0),0,'factory',9,6).ok).toBe(false);
});

test('drag blueprints and map ghosts turn red or green, drop once and preserve the camera',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('crystalSound','off'));await page.setViewportSize({width:440,height:956});await page.goto('/crystal-command.html');await page.locator('#practice').click();await page.locator('#buildTab').click();
 await page.evaluate(()=>CrystalGame.issue({type:'stop',ids:CrystalGame.view.entities.filter(e=>e.side===0&&e.type==='worker').map(e=>e.id)}));
 const before=await page.evaluate(()=>({funds:CrystalGame.state.players[0].crystals,point:CrystalGame.renderer.point(6,6)})),b=await page.locator('[data-kind=factory]').boundingBox(),c=await page.locator('#battle').boundingBox();const bad=await page.evaluate(()=>CrystalGame.renderer.point(6,6));
 await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(c.x+bad.x,c.y+bad.y,{steps:8});await expect.poll(()=>page.evaluate(()=>CrystalGame.placementPreview?.ok)).toBe(false);await expect.poll(()=>page.evaluate(()=>CrystalGame.placementPreview?.message)).toContain('clear');await page.screenshot({path:`test-results/crystal-build-red-${test.info().project.name}.png`});await page.mouse.up();
 expect(await page.evaluate(()=>CrystalGame.state.entities.filter(e=>e.side===0&&e.type==='factory').length)).toBe(0);expect(await page.evaluate(()=>CrystalGame.state.players[0].crystals)).toBe(before.funds);await expect(page.locator('#cancelBuild')).toBeVisible();
 const good=await page.evaluate(()=>CrystalGame.renderer.point(9,6));await page.mouse.move(c.x+bad.x,c.y+bad.y);await page.mouse.down();await page.mouse.move(c.x+good.x,c.y+good.y,{steps:8});await expect.poll(()=>page.evaluate(()=>CrystalGame.placementPreview?.ok)).toBe(true);expect(await page.evaluate(()=>CrystalGame.renderer.point(6,6))).toEqual(before.point);await page.screenshot({path:`test-results/crystal-build-green-${test.info().project.name}.png`});await page.mouse.up();
 expect(await page.evaluate(()=>CrystalGame.state.entities.filter(e=>e.side===0&&e.type==='factory').length)).toBe(1);expect(await page.evaluate(()=>CrystalGame.state.players[0].crystals)).toBe(before.funds-180);await expect(page.locator('#cancelBuild')).toBeHidden();await expect(page.locator('#message')).toContainText('assembling');expect(await page.evaluate(()=>CrystalGame.placementPreview)).toBeNull();
 expect(errors).toEqual([]);
});

test('touch blueprint drops outside the field and canceled map gestures spend no crystals',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('crystalSound','off'));await page.setViewportSize({width:320,height:568});await page.goto('/crystal-command.html');await page.locator('#practice').click();await page.locator('#buildTab').click();
 await page.locator('[data-kind=factory]').evaluate(b=>{const original=b.setPointerCapture.bind(b);b.setPointerCapture=id=>{try{original(id)}catch{}}});
 const pos=await page.locator('[data-kind=factory]').boundingBox();await page.locator('[data-kind=factory]').dispatchEvent('pointerdown',{pointerId:96,pointerType:'touch',button:0,clientX:pos.x+pos.width/2,clientY:pos.y+pos.height/2});await page.locator('[data-kind=factory]').dispatchEvent('pointermove',{pointerId:96,pointerType:'touch',button:0,clientX:10,clientY:pos.y+20});await page.locator('[data-kind=factory]').dispatchEvent('pointerup',{pointerId:96,pointerType:'touch',button:0,clientX:10,clientY:pos.y+20});
 expect(await page.evaluate(()=>CrystalGame.state.entities.some(e=>e.type==='factory'&&e.side===0))).toBe(false);await expect(page.locator('#cancelBuild')).toBeVisible();await expect(page.locator('#message')).toContainText('battlefield');
 const p=await page.evaluate(()=>CrystalGame.renderer.point(9,6));await touchBox(page,p,{x:p.x+5,y:p.y+5},{cancel:true});expect(await page.evaluate(()=>CrystalGame.placementPreview)).toBeNull();await page.locator('#cancelBuild').click();await expect(page.locator('#cancelBuild')).toBeHidden();expect(await page.evaluate(()=>CrystalGame.state.entities.some(e=>e.type==='factory'&&e.side===0))).toBe(false);const quit=await page.locator('#quit').boundingBox();expect(quit.y+quit.height).toBeLessThanOrEqual(568);
 await page.evaluate(()=>CrystalGame.issue({type:'stop',ids:CrystalGame.view.entities.filter(e=>e.side===0&&e.type==='worker').map(e=>e.id)}));const funds=await page.evaluate(()=>CrystalGame.state.players[0].crystals),field=await page.locator('#battle').boundingBox(),site=await page.evaluate(()=>CrystalGame.renderer.point(9,6));
 await page.locator('[data-kind=factory]').dispatchEvent('pointerdown',{pointerId:97,pointerType:'touch',button:0,clientX:pos.x+pos.width/2,clientY:pos.y+pos.height/2});await page.locator('[data-kind=factory]').dispatchEvent('pointermove',{pointerId:97,pointerType:'touch',button:0,clientX:field.x+site.x,clientY:field.y+site.y});expect(await page.evaluate(()=>CrystalGame.placementPreview?.ok)).toBe(true);await page.locator('[data-kind=factory]').dispatchEvent('pointerup',{pointerId:97,pointerType:'touch',button:0,clientX:field.x+site.x,clientY:field.y+site.y});expect(await page.evaluate(()=>CrystalGame.state.entities.filter(e=>e.type==='factory'&&e.side===0).length)).toBe(1);expect(await page.evaluate(()=>CrystalGame.state.players[0].crystals)).toBe(funds-180);
});
