const {test,expect}=require('@playwright/test');
const E=require('../crystal-command-engine');
function advance(s,seconds){for(let i=0;i<Math.round(seconds/E.STEP)&&!s.ended;i++)E.tick(s)}
test('workers deliver finite crystals and two armies start hidden',()=>{const s=E.create();expect(s.entities.filter(e=>e.side===0&&e.type==='worker')).toHaveLength(4);expect(E.view(s,0).entities.some(e=>e.side===1)).toBe(false);const total=s.crystals.reduce((n,c)=>n+c.left,0);advance(s,20);expect(s.players[0].mined).toBeGreaterThan(0);expect(s.crystals.reduce((n,c)=>n+c.left,0)+s.entities.reduce((n,e)=>n+e.carry,0)+s.players.reduce((n,p)=>n+p.mined,0)).toBe(total)});
test('construction, unit prerequisites and supply prevent button-spam armies',()=>{const s=E.create();const base=s.entities.find(e=>e.side===0&&e.type==='base');expect(E.command(s,0,{type:'train',id:base.id,kind:'siege'}).ok).toBe(false);expect(E.command(s,0,{type:'build',kind:'factory',x:9,y:6}).ok).toBe(true);expect(E.command(s,0,{type:'build',kind:'factory',x:9,y:6}).ok).toBe(false);const f=s.entities.find(e=>e.side===0&&e.type==='factory');expect(E.command(s,0,{type:'train',id:f.id,kind:'laser'}).ok).toBe(false);advance(s,12);s.players[0].crystals=10000;expect(E.command(s,0,{type:'train',id:f.id,kind:'siege'}).ok).toBe(false);for(let i=0;i<20;i++)E.command(s,0,{type:'train',id:f.id,kind:'laser'});expect(f.queue.length).toBe(5);advance(s,40);for(let i=0;i<20;i++)E.command(s,0,{type:'train',id:f.id,kind:'laser'});expect(E.supply(s,0).used).toBeLessThanOrEqual(16)});
test('orders validate owner, fog, coordinates and payload size',()=>{const s=E.create();const enemy=s.entities.find(e=>e.side===1&&e.type==='worker');expect(E.command(s,0,{type:'move',ids:[enemy.id],x:10,y:10}).ok).toBe(false);expect(E.command(s,0,{type:'build',kind:'base',x:33,y:33}).ok).toBe(false);expect(E.command(s,0,{type:'move',ids:Array(100).fill(1),x:NaN,y:1}).ok).toBe(false);expect(E.command(s,0,{type:'train',id:1,kind:'toString'}).ok).toBe(false);expect(E.command(s,0,{type:'build',kind:'toString',x:9,y:6}).ok).toBe(false);expect(Number.isFinite(s.players[0].crystals)).toBe(true)});
test('scouting reveals units and attack-move can destroy a rival base',()=>{const s=E.create();const army=s.entities.find(e=>e.side===0&&e.type==='worker');army.type='siege';army.hp=250;army.x=31;army.y=31;advance(s,.1);expect(E.view(s,0).entities.some(e=>e.side===1)).toBe(true);E.command(s,0,{type:'attack',ids:[army.id],x:33,y:33});advance(s,130);expect(s.ended).toBe(true);expect(s.winner).toBe(0)});
test('mining and combat produce deterministic state and idle practice loses',()=>{const a=E.create({practice:true}),b=E.create({practice:true});advance(a,140);advance(b,140);expect(E.view(a,0)).toEqual(E.view(b,0));expect(a.ended).toBe(true);expect(a.winner).toBe(1);expect(a.time).toBeLessThan(140)});
test('tactical paths avoid rocks and exhausted crystals cannot mint income',()=>{const s=E.create();const p=E.path(s,{x:10,y:12},{x:14,y:12});expect(p.length).toBeGreaterThan(4);expect(p.some(t=>s.rocks.some(r=>r.x===Math.floor(t.x)&&r.y===Math.floor(t.y)))).toBe(false);s.crystals.forEach(n=>n.left=0);advance(s,10);expect(s.players[0].crystals).toBe(250)});
test('mobile strategy controls, pause and quit confirmation work',async({page})=>{
 await page.goto('/crystal-command.html');await page.getByRole('button',{name:'▶ Practice battle'}).click();await expect(page.locator('#lobby')).toBeHidden();await expect(page.locator('.public-footer')).toBeHidden();await expect(page.locator('#crystals')).not.toHaveText('250',{timeout:15000});await page.getByRole('button',{name:'Build',exact:true}).click();await page.locator('#palette').getByRole('button',{name:/War factory/}).click();await expect(page.locator('#context')).toContainText('Place War factory');await page.locator('#pause').click();const tick=await page.evaluate(()=>CrystalGame.view.tick);await page.waitForTimeout(300);expect(await page.evaluate(()=>CrystalGame.view.tick)).toBe(tick);await page.locator('#pause').click();await page.locator('#quit').click();await expect(page.locator('#confirm')).toBeVisible();await page.getByRole('button',{name:'Keep playing'}).click();await expect(page.locator('#confirm')).toBeHidden();expect(await page.evaluate(()=>CrystalGame.running)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/crystal-command-${test.info().project.name}.png`});await page.locator('#quit').click();await page.getByRole('button',{name:'Quit battle',exact:true}).click();await expect(page.locator('#results')).toBeVisible();await expect(page.locator('.public-footer')).toBeVisible();
});
test('friend rooms show a useful sign-in requirement to guests',async({page})=>{await page.goto('/crystal-command.html');await page.locator('#createRoom').click();await expect(page.locator('#lobbyError')).toContainText('Sign in');await expect(page.locator('#authLink')).toBeVisible()});
