const {test,expect}=require('@playwright/test');
const E=require('../crystal-command-engine');
const advance=(s,t)=>{for(let i=0;i<Math.round(t/E.STEP)&&!s.ended;i++)E.tick(s)};
function add(s,type,side,x,y){const sample=s.entities.find(e=>e.type==='worker')||s.entities[0],d=E.TYPES[type],e={...sample,id:s.next++,type,side,x,y,hp:d.hp,maxHp:d.hp,build:0,path:[],queue:[],order:{type:'stop'},rally:null,research:null,cool:0,carry:0,mine:0};s.entities.push(e);return e}
test('expanded production requires completed owned tech and reserves air supply',()=>{
 const s=E.create();s.players[0].crystals=10000;const base=s.entities.find(e=>e.side===0&&e.type==='base');
 expect(E.placement(s,0,'starport',9,6).message).toContain('War factory');const f=add(s,'factory',0,9,6);f.build=2;expect(E.placement(s,0,'starport',9,10).ok).toBe(false);f.build=0;
 expect(E.command(s,0,{type:'build',kind:'starport',x:9,y:10}).ok).toBe(true);const port=s.entities.find(e=>e.side===0&&e.type==='starport');expect(E.command(s,0,{type:'train',id:port.id,kind:'interceptor'}).ok).toBe(false);advance(s,15);
 const bay=add(s,'barracks',0,6,10);expect(E.command(s,0,{type:'train',id:base.id,kind:'interceptor'}).ok).toBe(false);expect(E.command(s,0,{type:'train',id:f.id,kind:'guardian'}).message).toContain('Arsenal');expect(E.command(s,0,{type:'train',id:port.id,kind:'bomber'}).message).toContain('Arsenal');
 const arsenal=add(s,'armory',1,35,29);expect(E.command(s,0,{type:'train',id:f.id,kind:'guardian'}).ok).toBe(false);arsenal.side=0;expect(E.command(s,0,{type:'train',id:port.id,kind:'cruiser'}).message).toContain('Tech core');add(s,'lab',0,10,3);for(let i=0;i<3;i++)add(s,'relay',0,20+i*2,4);
 for(const [id,kind]of [[bay.id,'raider'],[bay.id,'medic'],[f.id,'guardian'],[port.id,'interceptor'],[port.id,'bomber'],[port.id,'cruiser']])expect(E.command(s,0,{type:'train',id,kind}).ok).toBe(true);
 expect(E.supply(s,0).used).toBe(21);expect(E.command(s,0,{type:'rally',id:port.id,x:12,y:12}).ok).toBe(true);expect(E.command(s,0,{type:'rally',id:f.id,x:12,y:12}).ok).toBe(false);advance(s,45);
 for(const type of ['raider','medic','guardian','interceptor','bomber','cruiser'])expect(s.entities.some(e=>e.type===type&&e.side===0)).toBe(true);expect(E.supply(s,0).used).toBe(21);
 s.entities=s.entities.filter(e=>e.side!==0||e.type!=='relay');expect(E.command(s,0,{type:'train',id:port.id,kind:'cruiser'}).message).toContain('Supply');
});
test('air crosses rocks and ground-only units cannot focus or splash aircraft',()=>{
 const s=E.create(),fighter=add(s,'interceptor',0,10,12),siege=add(s,'siege',0,10,10),enemyAir=add(s,'interceptor',1,11,10),enemyGround=add(s,'raider',1,11,10);enemyAir.cool=enemyGround.cool=100;
 E.tick(s);expect(E.command(s,0,{type:'attack',ids:[siege.id],x:enemyAir.x,y:enemyAir.y,target:enemyAir.id}).message).toContain('cannot attack air');siege.cool=0;const hp=enemyAir.hp;advance(s,.1);expect(enemyAir.hp).toBe(hp);expect(enemyGround.hp).toBeLessThan(enemyGround.maxHp);
 E.command(s,0,{type:'move',ids:[fighter.id],x:12.5,y:12.5});advance(s,1);expect(fighter.x).toBeCloseTo(12.5);expect(fighter.y).toBeCloseTo(12.5);expect(fighter.path).toEqual([]);
 const bomber=add(s,'bomber',0,10,10);expect(E.canTarget(bomber,enemyAir)).toBe(false);expect(E.canTarget(bomber,enemyGround)).toBe(true);expect(E.canTarget(add(s,'flak',0,15,15),enemyGround)).toBe(false);expect(E.canTarget(add(s,'guardian',0,15,15),enemyAir)).toBe(true);
});
test('medics heal ground allies only, never overheal or prevent move-only orders',()=>{
 const s=E.create(),medic=add(s,'medic',0,9,6),patient=add(s,'laser',0,9,7),air=add(s,'interceptor',0,9,7),base=s.entities.find(e=>e.side===0&&e.type==='base');patient.hp=50;air.hp=50;base.hp=800;advance(s,2.2);expect(patient.hp).toBe(74);expect(air.hp).toBe(50);expect(base.hp).toBe(800);expect(E.view(s,0).visualEvents.some(e=>e.type==='heal')).toBe(true);
 patient.hp=119;advance(s,2);expect(patient.hp).toBe(120);patient.hp=50;E.command(s,0,{type:'move',ids:[medic.id],x:15,y:8});const before=medic.x;advance(s,1);expect(medic.x).toBeGreaterThan(before);expect(patient.hp).toBe(50);
});
test('air remains hidden outside vision and its combat events identify both layers',()=>{
 const s=E.create(),hidden=add(s,'cruiser',1,33,32);expect(E.view(s,0).version).toBe(4);expect(E.view(s,0).entities.some(e=>e.id===hidden.id)).toBe(false);
 const a=add(s,'interceptor',0,9,6),b=add(s,'interceptor',1,10,6);b.cool=100;E.tick(s);const shot=s.events.find(e=>e.type==='shot'&&e.kind==='interceptor'&&e.side===0);expect(shot.air).toBe(true);expect(shot.targetAir).toBe(true);expect(b.hp).toBe(b.maxHp-E.TYPES.interceptor.airDamage);expect(E.view(s,0).entities.some(e=>e.id===hidden.id)).toBe(false);
});
test('phone advanced deck, aircraft production, elevated box selection and radar orders work',async({page})=>{
 test.setTimeout(60000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:320,height:568});await page.goto('/crystal-command.html');await page.locator('#practice').click();await page.locator('#buildTab').click();await page.locator('[data-group=advanced]').click();await expect(page.locator('[data-kind=starport]')).toBeDisabled();await expect(page.locator('[data-kind=starport]')).toContainText('Needs War factory');await expect(page.locator('#palette button')).toHaveCount(4);
 for(const r of await page.locator('#palette button').evaluateAll(bs=>bs.map(b=>{const r=b.getBoundingClientRect();return{x:r.x,right:r.right}})))expect(r.x>=0&&r.right<=320).toBe(true);expect((await page.locator('#quit').boundingBox()).y+(await page.locator('#quit').boundingBox()).height).toBeLessThanOrEqual(568);
 await page.locator('#pause').click();const tick=await page.evaluate(()=>{const s=CrystalGame.state;s.botAt=Infinity;s.players[0].crystals=10000;for(const [kind,x,y]of [['factory',9,6],['lab',6,10],['relay',10,3]]){const r=CrystalCommand.command(s,0,{type:'build',kind,x,y});if(!r.ok)throw Error(r.message)}for(let i=0;i<330;i++)CrystalCommand.tick(s);return s.tick});await page.locator('#pause').click();await page.waitForFunction(t=>CrystalGame.view.tick>t,tick);await expect(page.locator('[data-kind=starport]')).toBeEnabled();
 const card=await page.locator('[data-kind=starport]').boundingBox(),canvas=await page.locator('#battle').boundingBox(),spot=await page.evaluate(()=>CrystalGame.renderer.point(9,10));await page.mouse.move(card.x+card.width/2,card.y+card.height/2);await page.mouse.down();await page.mouse.move(canvas.x+spot.x,canvas.y+spot.y,{steps:5});await page.waitForFunction(()=>CrystalGame.placementPreview?.ok);await page.mouse.up();await page.waitForFunction(()=>CrystalGame.state.entities.some(e=>e.type==='starport'&&!e.build),{},{timeout:20000});await page.evaluate(()=>CrystalGame.renderer.center(9,10));const port=await page.evaluate(()=>CrystalGame.renderer.point(9,10,.4));await page.locator('#battle').click({position:port});await expect(page.locator('#selectionName')).toHaveText('Star hangar');await expect(page.locator('#palette svg')).toHaveCount(3);await expect(page.locator('#setRally')).toBeVisible();await expect(page.locator('[data-kind=bomber]')).toBeDisabled();await expect(page.locator('[data-kind=cruiser]')).toContainText('Needs Arsenal');
 await page.locator('[data-kind=interceptor]').click();await page.waitForFunction(()=>CrystalGame.view.entities.some(e=>e.type==='interceptor'),{},{timeout:15000});const unit=await page.evaluate(()=>CrystalGame.view.entities.find(e=>e.type==='interceptor'));await page.evaluate(u=>CrystalGame.renderer.center(u.x,u.y),unit);await page.locator('#boxSelect').click();const p=await page.evaluate(u=>CrystalGame.renderer.point(u.x,u.y,1.4),unit),field=await page.locator('#battle').boundingBox();await page.mouse.move(field.x+p.x-12,field.y+p.y-12);await page.mouse.down();await page.mouse.move(field.x+p.x+12,field.y+p.y+12,{steps:4});await page.mouse.up();expect(await page.evaluate(id=>CrystalGame.selection.includes(id),unit.id)).toBe(true);await expect(page.locator('#selectionDetail')).toContainText('AIR');
 await page.screenshot({path:`test-results/crystal-air-${test.info().project.name}.png`});const mini=await page.evaluate(()=>CrystalGame.renderer.minimapBounds);await page.locator('#battle').click({position:{x:mini.x+mini.w*.3,y:mini.y+mini.h*.3}});await page.waitForFunction(id=>CrystalGame.state.entities.find(e=>e.id===id).order?.type==='attack',unit.id);expect(errors).toEqual([]);
});
test('expanded models and healing effects render cleanly and freeze with pause',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:440,height:956});await page.goto('/crystal-command.html');await page.locator('#practice').click();await page.locator('#pause').click();const tick=await page.evaluate(()=>{const s=CrystalGame.state,sample=s.entities.find(e=>e.type==='worker');s.botAt=Infinity;for(const [type,x,y]of [['raider',5,8],['medic',7,8],['guardian',9,8],['interceptor',5,6],['bomber',7,6],['cruiser',9,6],['starport',10,3],['armory',6,11],['barracks',3,10],['flak',10,11]]){const d=CrystalCommand.TYPES[type];s.entities.push({...sample,id:s.next++,type,side:0,x,y,hp:d.hp,maxHp:d.hp,order:{type:'stop'},path:[],queue:[],build:0})}const patient=s.entities.find(e=>e.type==='raider');patient.hp=50;CrystalCommand.tick(s);return s.tick});await page.locator('#pause').click();await page.waitForFunction(t=>CrystalGame.view.tick>t,tick);await page.locator('#zoomOut').click();await page.locator('#zoomOut').click();await page.screenshot({path:`test-results/crystal-expanded-forces-${test.info().project.name}.png`});await page.locator('#pause').click();await page.waitForTimeout(100);const image=await page.locator('#battle').evaluate(c=>c.toDataURL());await page.waitForTimeout(200);expect(await page.locator('#battle').evaluate(c=>c.toDataURL())).toBe(image);expect(errors).toEqual([]);
});
test('practice tech branches find clear sites and include aircraft within the Easy army cap',()=>{
 const s=E.create({practice:true,difficulty:'easy'});s.entities.find(e=>e.side===0&&e.type==='base').hp=100000000;advance(s,330);expect(s.entities.some(e=>e.side===1&&e.type==='starport'&&!e.build)).toBe(true);expect(s.entities.some(e=>e.side===1&&E.TYPES[e.type].flying)).toBe(true);expect(s.entities.filter(e=>e.side===1&&E.TYPES[e.type].supply&&e.type!=='worker').length+s.entities.filter(e=>e.side===1).reduce((n,e)=>n+e.queue.filter(k=>k!=='worker').length,0)).toBeLessThanOrEqual(E.DIFFICULTIES.easy.armyCap);
});
