"""Rebuild the original, locally synthesized robot voice bank with espeak-ng + NumPy.
ESPEAK_BIN can point at a portable installation. No external voice or likeness used.
"""
import base64, json, os, subprocess, tempfile, wave
from pathlib import Path
import numpy as np
LINES = {
 'acquired':'Target acquired.', 'pursuit':'Initiating pursuit.',
 'resistance':'Resistance is illogical.', 'heavy':'Heavy unit online.',
 'hide':'You cannot hide.', 'failing':'Systems failing.',
 'shield':'Shield online.', 'overdrive':'Overdrive engaged.',
 'critical':'Warning. Hull critical.', 'complete':'Breach complete.'
}
rate=16000
pcm=bytearray(); clips={}
with tempfile.TemporaryDirectory() as folder:
 for key, text in LINES.items():
  file=Path(folder)/f'{key}.wav'
  subprocess.run([os.environ.get('ESPEAK_BIN','espeak-ng'),'-v','en-us+m3','-s','148','-p','28','-a','150','-w',str(file),text],check=True)
  with wave.open(str(file)) as w:
   source_rate=w.getframerate(); samples=np.frombuffer(w.readframes(w.getnframes()),dtype='<i2').astype(float)/32768
  # Trim silence, retain natural consonants, add a metallic dual-frequency ring.
  active=np.flatnonzero(np.abs(samples)>.007)
  samples=samples[max(0,active[0]-300):min(len(samples),active[-1]+600)]
  samples=np.interp(np.arange(0,len(samples),source_rate/rate),np.arange(len(samples)),samples)
  t=np.arange(len(samples))/rate
  samples=np.tanh(samples*1.5)*(.76+.16*np.sin(2*np.pi*43*t)+.08*np.sin(2*np.pi*89*t))
  echo=int(rate*.036); samples[echo:]+=samples[:-echo]*.16
  samples*=.84/max(.01,np.max(np.abs(samples)))
  fade=min(100,len(samples)//2);samples[:fade]*=np.linspace(0,1,fade);samples[-fade:]*=np.linspace(1,0,fade)
  clip=np.clip(np.round(samples*127+128),0,255).astype('uint8').tobytes()
  clips[key]={'text':text,'start':len(pcm),'length':len(clip)}; pcm.extend(clip)
bank={'rate':rate,'clips':clips,'pcm':base64.b64encode(pcm).decode()}
output=Path(__file__).resolve().parents[1]/'neonbreach-voices.js'
output.write_text('// Original robot voice clips generated by scripts/generate-neonbreach-voices.py\nwindow.NeonBreachVoices='+json.dumps(bank,separators=(',',':'))+';\n')
print(f'{len(clips)} clips, {len(pcm)/rate:.1f}s, {output.stat().st_size} bytes')
