-- Independent potato features. Existing ownership, prices, balances and loadouts stay intact.
ALTER TABLE public.cosmetic_items DROP CONSTRAINT cosmetic_items_slot_check;
ALTER TABLE public.cosmetic_items ADD CONSTRAINT cosmetic_items_slot_check CHECK(slot IN ('avatar','outfit','weapon','shoes','backpack','face','beard','head','eyes','brows','nose','mouth','hair','marks'));
ALTER TABLE public.cosmetic_loadouts DROP CONSTRAINT cosmetic_loadouts_slot_check;
ALTER TABLE public.cosmetic_loadouts ADD CONSTRAINT cosmetic_loadouts_slot_check CHECK(slot IN ('avatar','outfit','weapon','shoes','backpack','face','beard','head','eyes','brows','nose','mouth','hair','marks'));
INSERT INTO public.cosmetic_items(id,name,slot,coin_price,rarity,asset_path,is_starter) VALUES
 ('russet-potato','Russet Potato','avatar',0,'common','cosmetic-russet-potato.svg',false),
 ('cream-potato','Cream Potato','avatar',0,'common','cosmetic-cream-potato.svg',false),
 ('rose-potato','Rose Potato','avatar',0,'common','cosmetic-rose-potato.svg',false),
 ('eyes-classic','Bright Eyes','eyes',0,'common','cosmetic-eyes-classic.svg',true),
 ('eyes-hazel','Hazel Eyes','eyes',0,'common','cosmetic-eyes-hazel.svg',false),
 ('eyes-green','Clover Eyes','eyes',0,'common','cosmetic-eyes-green.svg',false),
 ('eyes-lashes','Soft Lashes','eyes',0,'common','cosmetic-eyes-lashes.svg',false),
 ('eyes-happy','Happy Eyes','eyes',0,'common','cosmetic-eyes-happy.svg',false),
 ('eyes-amber','Amber Lashes','eyes',0,'common','cosmetic-eyes-amber.svg',false),
 ('eyes-galaxy','Galaxy Eyes','eyes',500,'rare','cosmetic-eyes-galaxy.svg',false),
 ('brows-classic','Friendly Brows','brows',0,'common','cosmetic-brows-classic.svg',true),
 ('brows-soft','Soft Arches','brows',0,'common','cosmetic-brows-soft.svg',false),
 ('brows-bold','Bold Brows','brows',0,'common','cosmetic-brows-bold.svg',false),
 ('brows-curious','Curious Brows','brows',0,'common','cosmetic-brows-curious.svg',false),
 ('brows-daring','Daring Brows','brows',0,'common','cosmetic-brows-daring.svg',false),
 ('brows-none','No Brows','brows',0,'common','cosmetic-brows-none.svg',false),
 ('mouth-smile','Classic Smile','mouth',0,'common','cosmetic-mouth-smile.svg',true),
 ('mouth-grin','Big Grin','mouth',0,'common','cosmetic-mouth-grin.svg',false),
 ('mouth-soft','Soft Smile','mouth',0,'common','cosmetic-mouth-soft.svg',false),
 ('mouth-rose','Rose Smile','mouth',0,'common','cosmetic-mouth-rose.svg',false),
 ('mouth-wow','Little Wow','mouth',0,'common','cosmetic-mouth-wow.svg',false),
 ('mouth-smirk','Cheeky Smirk','mouth',0,'common','cosmetic-mouth-smirk.svg',false),
 ('mouth-vampire','Tiny Fangs','mouth',250,'rare','cosmetic-mouth-vampire.svg',false),
 ('nose-classic','Button Nose','nose',0,'common','cosmetic-nose-classic.svg',true),
 ('nose-round','Round Nose','nose',0,'common','cosmetic-nose-round.svg',false),
 ('nose-tiny','Tiny Nose','nose',0,'common','cosmetic-nose-tiny.svg',false),
 ('nose-freckle','Freckled Nose','nose',0,'common','cosmetic-nose-freckle.svg',false),
 ('hair-sprout','Just a Sprout','hair',0,'common','cosmetic-hair-sprout.svg',true),
 ('hair-bob','Chestnut Bob','hair',0,'common','cosmetic-hair-bob.svg',false),
 ('hair-sweep','Side Sweep','hair',0,'common','cosmetic-hair-sweep.svg',false),
 ('hair-ponytail','Golden Ponytail','hair',0,'common','cosmetic-hair-ponytail.svg',false),
 ('hair-curls','Cocoa Curls','hair',0,'common','cosmetic-hair-curls.svg',false),
 ('hair-waves','Rose Waves','hair',0,'common','cosmetic-hair-waves.svg',false),
 ('hair-aurora','Aurora Waves','hair',650,'legendary','cosmetic-hair-aurora.svg',false),
 ('marks-natural','Natural Dimples','marks',0,'common','cosmetic-marks-natural.svg',true),
 ('marks-freckles','Extra Freckles','marks',0,'common','cosmetic-marks-freckles.svg',false),
 ('marks-blush','Rosy Cheeks','marks',0,'common','cosmetic-marks-blush.svg',false),
 ('marks-heart','Heart Sticker','marks',0,'common','cosmetic-marks-heart.svg',false),
 ('marks-starlight','Starlight Freckles','marks',350,'rare','cosmetic-marks-starlight.svg',false),
 ('garden-overalls','Garden Overalls','outfit',0,'common','cosmetic-garden-overalls.svg',false),
 ('petal-dress','Petal Dress','outfit',0,'common','cosmetic-petal-dress.svg',false),
 ('moonwalker-suit','Moonwalker Suit','outfit',800,'legendary','cosmetic-moonwalker-suit.svg',false),
 ('royal-petal','Royal Petal','outfit',900,'legendary','cosmetic-royal-petal.svg',false),
 ('no-handheld','Empty Hands','weapon',0,'common','cosmetic-no-handheld.svg',false)
ON CONFLICT(id) DO NOTHING;
